import type { Item } from "./types";

const list: Item[] = [
  // ---------------- weapons ----------------
  {
    id: "rusty_sword",
    name: "Rusty Sword",
    category: "weapons",
    sprite: "sword",
    weight: 8,
    value: 15,
    description: "It has seen better centuries.",
    damage: 4,
    scaling: "strength",
    slot: "weapon",
  },
  {
    id: "iron_sword",
    name: "Iron Sword",
    category: "weapons",
    sprite: "sword",
    weight: 9,
    value: 60,
    description: "A dependable blade of honest iron.",
    damage: 8,
    scaling: "strength",
    slot: "weapon",
  },
  {
    id: "steel_axe",
    name: "Steel Axe",
    category: "weapons",
    sprite: "axe",
    weight: 12,
    value: 120,
    description: "Chops wood. Chops other things too.",
    damage: 13,
    scaling: "strength",
    slot: "weapon",
  },
  {
    id: "shadow_dagger",
    name: "Shadow Dagger",
    category: "weapons",
    sprite: "dagger",
    weight: 3,
    value: 140,
    description: "Light as a whisper, sharp as a grudge.",
    damage: 10,
    scaling: "dexterity",
    slot: "weapon",
  },
  {
    id: "apprentice_staff",
    name: "Apprentice Staff",
    category: "weapons",
    sprite: "staff",
    weight: 5,
    value: 70,
    description: "Hums faintly with stored arcana.",
    damage: 7,
    scaling: "intelligence",
    slot: "weapon",
  },
  {
    id: "arch_staff",
    name: "Archmage Staff",
    category: "weapons",
    sprite: "staff",
    weight: 6,
    value: 260,
    description: "The amethyst on top is definitely watching you.",
    damage: 14,
    scaling: "intelligence",
    slot: "weapon",
  },
  {
    id: "dragonbane",
    name: "Dragonbane",
    category: "weapons",
    sprite: "sword",
    weight: 11,
    value: 500,
    description: "Forged for exactly one purpose. You will know when.",
    damage: 19,
    scaling: "strength",
    slot: "weapon",
  },
  // ---------------- apparel ----------------
  {
    id: "leather_armor",
    name: "Leather Armor",
    category: "apparel",
    sprite: "armor",
    weight: 10,
    value: 45,
    description: "Smells like adventure. And cow.",
    armor: 3,
    slot: "body",
  },
  {
    id: "iron_armor",
    name: "Iron Armor",
    category: "apparel",
    sprite: "armor",
    weight: 22,
    value: 150,
    description: "Heavy, loud, and wonderfully stab-resistant.",
    armor: 6,
    slot: "body",
  },
  {
    id: "mage_robe",
    name: "Enchanted Robe",
    category: "apparel",
    sprite: "robe",
    weight: 4,
    value: 130,
    description: "Woven with wards. Machine wash cold.",
    armor: 4,
    slot: "body",
  },
  {
    id: "steel_shield",
    name: "Steel Shield",
    category: "apparel",
    sprite: "shield",
    weight: 12,
    value: 110,
    description: "The best offense's roommate.",
    armor: 3,
    slot: "offhand",
  },
  // ---------------- potions ----------------
  {
    id: "potion_hp",
    name: "Health Potion",
    category: "potions",
    sprite: "potion_hp",
    weight: 1,
    value: 25,
    description: "Restores 25 HP. Tastes like cherries and regret.",
    restoreHp: 25,
  },
  {
    id: "potion_mp",
    name: "Mana Potion",
    category: "potions",
    sprite: "potion_mp",
    weight: 1,
    value: 25,
    description: "Restores 15 MP. Fizzy.",
    restoreMp: 15,
  },
  {
    id: "elixir",
    name: "Elixir",
    category: "potions",
    sprite: "elixir",
    weight: 1,
    value: 60,
    description: "Restores 30 HP and 20 MP. The merchant swears by it.",
    restoreHp: 30,
    restoreMp: 20,
  },
  // ---------------- food ----------------
  {
    id: "bread",
    name: "Bread Loaf",
    category: "food",
    sprite: "bread",
    weight: 1,
    value: 4,
    description: "Restores 8 HP. Slightly stale, fully edible.",
    restoreHp: 8,
  },
  {
    id: "cheese_wheel",
    name: "Cheese Wheel",
    category: "food",
    sprite: "cheese",
    weight: 5,
    value: 12,
    description: "Restores 15 HP. Rolls beautifully downhill.",
    restoreHp: 15,
  },
  // ---------------- misc ----------------
  {
    id: "gold_pile",
    name: "Gold Coins",
    category: "misc",
    sprite: "gold",
    weight: 0,
    value: 1,
    description: "The universal language.",
  },
  {
    id: "gem",
    name: "Flawless Emerald",
    category: "misc",
    sprite: "gem",
    weight: 0,
    value: 200,
    description: "Worth a fortune to the right collector.",
  },
  {
    id: "dragon_scale",
    name: "Dragon Scale",
    category: "misc",
    sprite: "scale",
    weight: 2,
    value: 350,
    description: "Still warm. Proof of the deed.",
  },
];

export const ITEMS: Record<string, Item> = Object.fromEntries(list.map((i) => [i.id, i]));

export function getItem(id: string): Item {
  const item = ITEMS[id];
  if (!item) throw new Error(`Unknown item: ${id}`);
  return item;
}
