import type { Item } from "./types";

const list: Item[] = [
  // ---------------- weapons ----------------
  {
    id: "rusty_sword",
    name: "Rusty Sword",
    category: "weapons",
    sprite: "sword",
    weight: 8,
    value: 15,
    description: "It has seen better centuries.",
    damage: 4,
    scaling: "strength",
    slot: "weapon",
  },
  {
    id: "hunting_bow",
    name: "Hunting Bow",
    category: "weapons",
    sprite: "bow",
    weight: 5,
    value: 45,
    description: "Feeds a family. Also perforates goblins.",
    damage: 6,
    scaling: "dexterity",
    slot: "weapon",
  },
  {
    id: "longbow",
    name: "Longbow",
    category: "weapons",
    sprite: "bow",
    weight: 7,
    value: 220,
    description: "Taller than most of its owners.",
    damage: 14,
    scaling: "dexterity",
    slot: "weapon",
  },
  {
    id: "war_hammer",
    name: "War Hammer",
    category: "weapons",
    sprite: "hammer",
    weight: 16,
    value: 320,
    description: "Subtle as a landslide, twice as convincing.",
    damage: 17,
    scaling: "strength",
    slot: "weapon",
  },
  {
    id: "moon_wand",
    name: "Moon Wand",
    category: "weapons",
    sprite: "wand",
    weight: 2,
    value: 180,
    description: "Hums a little tune when the moon is out.",
    damage: 11,
    scaling: "intelligence",
    slot: "weapon",
  },
  {
    id: "iron_sword",
    name: "Iron Sword",
    category: "weapons",
    sprite: "sword",
    weight: 9,
    value: 60,
    description: "A dependable blade of honest iron.",
    damage: 8,
    scaling: "strength",
    slot: "weapon",
  },
  {
    id: "steel_axe",
    name: "Steel Axe",
    category: "weapons",
    sprite: "axe",
    weight: 12,
    value: 120,
    description: "Chops wood. Chops other things too.",
    damage: 13,
    scaling: "strength",
    slot: "weapon",
  },
  {
    id: "shadow_dagger",
    name: "Shadow Dagger",
    category: "weapons",
    sprite: "dagger",
    weight: 3,
    value: 140,
    description: "Light as a whisper, sharp as a grudge.",
    damage: 10,
    scaling: "dexterity",
    slot: "weapon",
  },
  {
    id: "apprentice_staff",
    name: "Apprentice Staff",
    category: "weapons",
    sprite: "staff",
    weight: 5,
    value: 70,
    description: "Hums faintly with stored arcana.",
    damage: 7,
    scaling: "intelligence",
    slot: "weapon",
  },
  {
    id: "arch_staff",
    name: "Archmage Staff",
    category: "weapons",
    sprite: "staff",
    weight: 6,
    value: 260,
    description: "The amethyst on top is definitely watching you.",
    damage: 14,
    scaling: "intelligence",
    slot: "weapon",
  },
  {
    id: "obsidian_blade",
    name: "Obsidian Blade",
    category: "weapons",
    sprite: "sword",
    weight: 12,
    value: 700,
    description: "Volcanic glass, sharper than regret and twice as dark.",
    damage: 25,
    scaling: "strength",
    slot: "weapon",
  },
  {
    id: "dragonbane",
    name: "Dragonbane",
    category: "weapons",
    sprite: "sword",
    weight: 11,
    value: 500,
    description: "Forged for exactly one purpose. You will know when.",
    damage: 19,
    scaling: "strength",
    slot: "weapon",
  },
  // ---------------- apparel ----------------
  {
    id: "leather_armor",
    name: "Leather Armor",
    category: "apparel",
    sprite: "armor",
    weight: 10,
    value: 45,
    description: "Smells like adventure. And cow.",
    armor: 3,
    slot: "body",
  },
  {
    id: "iron_armor",
    name: "Iron Armor",
    category: "apparel",
    sprite: "armor",
    weight: 22,
    value: 150,
    description: "Heavy, loud, and wonderfully stab-resistant.",
    armor: 6,
    slot: "body",
  },
  {
    id: "mage_robe",
    name: "Enchanted Robe",
    category: "apparel",
    sprite: "robe",
    weight: 4,
    value: 130,
    description: "Woven with wards. Machine wash cold.",
    armor: 4,
    slot: "body",
  },
  {
    id: "runic_armor",
    name: "Runic Armor",
    category: "apparel",
    sprite: "armor",
    weight: 18,
    value: 550,
    description: "Dwarven runes still glow when danger is near. They glow a lot down here.",
    armor: 9,
    slot: "body",
  },
  {
    id: "traveler_cloak",
    name: "Traveler's Cloak",
    category: "apparel",
    sprite: "cloak",
    weight: 3,
    value: 35,
    description: "Smells of campfires and long roads.",
    armor: 2,
    slot: "body",
  },
  {
    id: "shadow_cloak",
    name: "Shadow Cloak",
    category: "apparel",
    sprite: "cloak",
    weight: 4,
    value: 260,
    description: "The seamstress swears it was black when she started.",
    armor: 5,
    slot: "body",
  },
  {
    id: "tower_shield",
    name: "Tower Shield",
    category: "apparel",
    sprite: "shield",
    weight: 20,
    value: 300,
    description: "Less a shield, more a portable wall.",
    armor: 5,
    slot: "offhand",
  },
  {
    id: "steel_shield",
    name: "Steel Shield",
    category: "apparel",
    sprite: "shield",
    weight: 12,
    value: 110,
    description: "The best offense's roommate.",
    armor: 3,
    slot: "offhand",
  },
  // ---------------- potions ----------------
  {
    id: "potion_hp",
    name: "Health Potion",
    category: "potions",
    sprite: "potion_hp",
    weight: 1,
    value: 25,
    description: "Restores 25 HP. Tastes like cherries and regret.",
    restoreHp: 25,
  },
  {
    id: "potion_mp",
    name: "Mana Potion",
    category: "potions",
    sprite: "potion_mp",
    weight: 1,
    value: 25,
    description: "Restores 15 MP. Fizzy.",
    restoreMp: 15,
  },
  {
    id: "greater_potion",
    name: "Greater Health Potion",
    category: "potions",
    sprite: "potion_hp",
    weight: 1,
    value: 70,
    description: "Restores 60 HP. Brewed strong for those who go below.",
    restoreHp: 60,
  },
  {
    id: "elixir",
    name: "Elixir",
    category: "potions",
    sprite: "elixir",
    weight: 1,
    value: 60,
    description: "Restores 30 HP and 20 MP. The merchant swears by it.",
    restoreHp: 30,
    restoreMp: 20,
  },
  {
    id: "antidote",
    name: "Antidote",
    category: "potions",
    sprite: "potion_green",
    weight: 1,
    value: 30,
    description: "Cures poison and restores 5 HP. Tastes like swamp, works like magic.",
    restoreHp: 5,
    cures: "poison",
  },
  {
    id: "ember_salve",
    name: "Ember Salve",
    category: "potions",
    sprite: "salve",
    weight: 1,
    value: 30,
    description: "Cures burning and restores 5 HP. Apply liberally, scream less.",
    restoreHp: 5,
    cures: "burn",
  },
  // ---------------- food ----------------
  {
    id: "bread",
    name: "Bread Loaf",
    category: "food",
    sprite: "bread",
    weight: 1,
    value: 4,
    description: "Restores 8 HP. Slightly stale, fully edible.",
    restoreHp: 8,
  },
  {
    id: "cheese_wheel",
    name: "Cheese Wheel",
    category: "food",
    sprite: "cheese",
    weight: 5,
    value: 12,
    description: "Restores 15 HP. Rolls beautifully downhill.",
    restoreHp: 15,
  },
  {
    id: "apple",
    name: "Apple",
    category: "food",
    sprite: "apple",
    weight: 1,
    value: 3,
    description: "Restores 6 HP. Keeps the cleric away.",
    restoreHp: 6,
  },
  {
    id: "dried_meat",
    name: "Dried Meat",
    category: "food",
    sprite: "meat",
    weight: 1,
    value: 8,
    description: "Restores 14 HP. Chewy. Extremely chewy.",
    restoreHp: 14,
  },
  // ---------------- misc ----------------
  {
    id: "forest_herb",
    name: "Forest Herb",
    category: "misc",
    sprite: "herb",
    weight: 0,
    value: 6,
    description: "Bitter leaves the healers swear by. Foraged in the forest.",
  },
  {
    id: "marsh_reed",
    name: "Marsh Reed",
    category: "misc",
    sprite: "reed",
    weight: 0,
    value: 6,
    description: "Hollow, mana-soaked stems from the sunken marsh.",
  },
  {
    id: "ember_shard",
    name: "Ember Shard",
    category: "misc",
    sprite: "shard",
    weight: 0,
    value: 10,
    description: "A pebble of the mountain's anger. Warm forever. Found in the ash fields.",
  },
  {
    id: "wolf_pelt",
    name: "Wolf Pelt",
    category: "misc",
    sprite: "pelt",
    weight: 3,
    value: 40,
    description: "The tanner pays well for these.",
  },
  {
    id: "imp_horn",
    name: "Imp Horn",
    category: "misc",
    sprite: "horn",
    weight: 1,
    value: 90,
    description: "Still faintly warm. Collectors are weird.",
  },
  {
    id: "gold_pile",
    name: "Gold Coins",
    category: "misc",
    sprite: "gold",
    weight: 0,
    value: 1,
    description: "The universal language.",
  },
  {
    id: "gem",
    name: "Flawless Emerald",
    category: "misc",
    sprite: "gem",
    weight: 0,
    value: 200,
    description: "Worth a fortune to the right collector.",
  },
  {
    id: "dragon_scale",
    name: "Dragon Scale",
    category: "misc",
    sprite: "scale",
    weight: 2,
    value: 350,
    description: "Still warm. Proof of the deed.",
  },
  {
    id: "lich_crown",
    name: "Crown of the Deathless",
    category: "misc",
    sprite: "gold",
    weight: 1,
    value: 800,
    description: "Its previous owner has no further use for it. Probably.",
  },
  {
    id: "reed_buckler",
    name: "Reedwoven Buckler",
    category: "apparel",
    sprite: "shield",
    weight: 4,
    value: 55,
    description: "Marsh reeds woven tight enough to turn a blade. Crafted, never sold.",
    armor: 4,
    slot: "offhand",
  },
  {
    id: "beast_cleaver",
    name: "Beast Cleaver",
    category: "weapons",
    sprite: "axe",
    weight: 11,
    value: 130,
    description: "Pelts and horn make a savage edge. Crafted, never sold.",
    damage: 12,
    scaling: "strength",
    slot: "weapon",
  },
  {
    id: "emberwood_staff",
    name: "Emberwood Staff",
    category: "weapons",
    sprite: "wand",
    weight: 6,
    value: 140,
    description: "Ash-field shards bound in living wood. Crafted, never sold.",
    damage: 11,
    scaling: "intelligence",
    slot: "weapon",
  },
  {
    id: "wyrmfang_dagger",
    name: "Wyrmfang Dagger",
    category: "weapons",
    sprite: "dagger",
    weight: 4,
    value: 170,
    description: "A dragon's scale honed to a whisper. Crafted, never sold.",
    damage: 13,
    scaling: "dexterity",
    slot: "weapon",
  },
  {
    id: "scaled_mail",
    name: "Scaled Mail",
    category: "apparel",
    sprite: "armor",
    weight: 13,
    value: 220,
    description: "Dragonscale over boiled hide. Crafted, never sold.",
    armor: 9,
    slot: "body",
  },
  {
    id: "stamina_draught",
    name: "Stamina Draught",
    category: "potions",
    sprite: "potion_green",
    weight: 1,
    value: 30,
    description: "Bitter marsh brew that puts the wind back in you.",
    restoreMp: 25,
  },
  {
    id: "hunters_stew",
    name: "Hunter's Stew",
    category: "food",
    sprite: "meat",
    weight: 2,
    value: 35,
    description: "Meat, herbs, and no questions asked.",
    restoreHp: 40,
  },
  {
    id: "dragon_tonic",
    name: "Dragon Tonic",
    category: "potions",
    sprite: "elixir",
    weight: 1,
    value: 120,
    description: "Scale-steeped fire in a bottle. Restores nearly everything.",
    restoreHp: 60,
    restoreMp: 30,
  },
  {
    id: "deep_root",
    name: "Deep Root",
    category: "misc",
    sprite: "reed",
    weight: 0,
    value: 9,
    description: "Old-forest heartwood, dense as stone. The Deepwood yields it grudgingly.",
  },
  {
    id: "grave_moss",
    name: "Grave Moss",
    category: "misc",
    sprite: "herb",
    weight: 0,
    value: 10,
    description: "It only grows where something is buried. The Mirefen is full of it.",
  },
  {
    id: "troll_salve",
    name: "Troll Salve",
    category: "potions",
    sprite: "salve",
    weight: 1,
    value: 90,
    description: "Regrows what you were sure was gone. Restores 80 HP.",
    restoreHp: 80,
  },
  {
    id: "deeproot_bow",
    name: "Deeproot Bow",
    category: "weapons",
    sprite: "bow",
    weight: 5,
    value: 260,
    description: "Heartwood bent to a killing curve. Crafted, never sold.",
    damage: 15,
    scaling: "dexterity",
    slot: "weapon",
  },
  {
    id: "grave_ward",
    name: "Grave Ward",
    category: "apparel",
    sprite: "cloak",
    weight: 3,
    value: 240,
    description: "A mantle of moss and scale that death declines to touch. Crafted, never sold.",
    armor: 6,
    slot: "offhand",
  },
];


export const ITEMS: Record<string, Item> = Object.fromEntries(list.map((i) => [i.id, i]));

export function getItem(id: string): Item {
  const item = ITEMS[id];
  if (!item) throw new Error(`Unknown item: ${id}`);
  return item;
}
