import type { Role, RoleId } from "../types";

export const ROLES: Record<RoleId, Role> = {
  warrior: {
    id: "warrior",
    name: "Warrior",
    description: "Frontline bruiser. High health and defense, hits hard with steel.",
    sprite: "hero_warrior",
    baseStats: { maxHp: 42, maxMp: 8, strength: 9, intelligence: 3, dexterity: 5, defense: 5, endurance: 8 },
    resource: "endurance",
    growth: { maxHp: 7, maxMp: 1 },
    skills: [
      {
        name: "Power Strike",
        description: "A crushing blow dealing heavy physical damage.",
        mpCost: 4,
        kind: "damage",
        multiplier: 1.9,
        stat: "strength",
        unlockLevel: 1,
      },
      {
        name: "Shield Slam",
        description: "A staggering bash that can stun the enemy for a turn.",
        mpCost: 6,
        kind: "damage",
        multiplier: 1.1,
        stat: "strength",
        unlockLevel: 3,
        inflicts: { kind: "stun", chance: 0.55, turns: 1, power: 0 },
      },
      {
        name: "Berserk",
        description: "Reckless fury: massive damage, but it costs 8 HP.",
        mpCost: 5,
        hpCost: 8,
        kind: "damage",
        multiplier: 2.7,
        stat: "strength",
        unlockLevel: 6,
      },
    ],
  },
  mage: {
    id: "mage",
    name: "Mage",
    description: "Glass cannon. Fragile, but Fireball melts anything with a face.",
    sprite: "hero_mage",
    baseStats: { maxHp: 28, maxMp: 24, strength: 3, intelligence: 10, dexterity: 4, defense: 2, endurance: 3 },
    resource: "mana",
    growth: { maxHp: 4, maxMp: 5 },
    skills: [
      {
        name: "Fireball",
        description: "Hurls a fireball for heavy magic damage.",
        mpCost: 6,
        kind: "damage",
        multiplier: 2.2,
        stat: "intelligence",
        unlockLevel: 1,
      },
      {
        name: "Ignite",
        description: "Sets the enemy ablaze, burning it for several turns.",
        mpCost: 7,
        kind: "damage",
        multiplier: 1.2,
        stat: "intelligence",
        unlockLevel: 3,
        inflicts: { kind: "burn", chance: 0.9, turns: 3, power: 6 },
      },
      {
        name: "Frost Nova",
        description: "A blast of cold that can freeze the enemy solid.",
        mpCost: 9,
        kind: "damage",
        multiplier: 1.5,
        stat: "intelligence",
        unlockLevel: 6,
        inflicts: { kind: "stun", chance: 0.6, turns: 1, power: 0 },
      },
    ],
  },
  rogue: {
    id: "rogue",
    name: "Rogue",
    description: "Fast and sneaky. Great at fleeing, deadly with a backstab.",
    sprite: "hero_rogue",
    baseStats: { maxHp: 34, maxMp: 12, strength: 6, intelligence: 4, dexterity: 10, defense: 3, endurance: 6 },
    resource: "endurance",
    growth: { maxHp: 5, maxMp: 2 },
    skills: [
      {
        name: "Backstab",
        description: "Strikes a vital spot for heavy dexterity damage.",
        mpCost: 5,
        kind: "damage",
        multiplier: 2.0,
        stat: "dexterity",
        unlockLevel: 1,
      },
      {
        name: "Poison Blade",
        description: "A coated dagger that leaves the enemy poisoned.",
        mpCost: 6,
        kind: "damage",
        multiplier: 1.1,
        stat: "dexterity",
        unlockLevel: 3,
        inflicts: { kind: "poison", chance: 0.85, turns: 3, power: 5 },
      },
      {
        name: "Shadowstep",
        description: "Vanish and reappear behind the enemy for a devastating strike.",
        mpCost: 10,
        kind: "damage",
        multiplier: 3.0,
        stat: "dexterity",
        unlockLevel: 6,
      },
    ],
  },
  cleric: {
    id: "cleric",
    name: "Cleric",
    description: "Holy support. Sturdy enough, and Mend keeps you in the fight.",
    sprite: "hero_cleric",
    baseStats: { maxHp: 38, maxMp: 18, strength: 6, intelligence: 7, dexterity: 4, defense: 4, endurance: 4 },
    resource: "mana",
    growth: { maxHp: 6, maxMp: 4 },
    skills: [
      {
        name: "Mend",
        description: "Channels light to restore health.",
        mpCost: 5,
        kind: "heal",
        multiplier: 2.5,
        stat: "intelligence",
        unlockLevel: 1,
      },
      {
        name: "Smite",
        description: "Searing radiance burns the enemy.",
        mpCost: 6,
        kind: "damage",
        multiplier: 1.8,
        stat: "intelligence",
        unlockLevel: 3,
      },
      {
        name: "Sanctuary",
        description: "A ward of light that heals and purges all ailments.",
        mpCost: 10,
        kind: "heal",
        multiplier: 2.0,
        stat: "intelligence",
        unlockLevel: 6,
        cleanse: true,
      },
    ],
  },
};

/** The skills a hero of the given level can currently use. */
export function unlockedSkills(roleId: RoleId, level: number) {
  return ROLES[roleId].skills.filter((skill) => level >= skill.unlockLevel);
}
