import type { TileDef, TileId } from "./types";

/** Terrain that breathes: tile id -> its animation sheet in atlas.json. */
export const TILE_ANIMATIONS: Partial<Record<TileId, string>> = {
  water: "water_shimmer",
  grass: "grass_sway",
  forest: "forest_sway",
  flowers: "flowers_sway",
  marsh: "marsh_sway",
};

export const TILES: Record<TileId, TileDef> = {
  grass: { id: "grass", sprite: "tile_grass", walkable: true },
  forest: { id: "forest", sprite: "tile_forest", walkable: true },
  mountain: { id: "mountain", sprite: "tile_mountain", walkable: false },
  water: { id: "water", sprite: "tile_water", walkable: false },
  path: { id: "path", sprite: "tile_path", walkable: true },
  sand: { id: "sand", sprite: "tile_sand", walkable: true },
  bridge: { id: "bridge", sprite: "tile_bridge", walkable: true },
  marsh: { id: "marsh", sprite: "tile_marsh", walkable: true },
  ash: { id: "ash", sprite: "tile_ash", walkable: true },
  wall: { id: "wall", sprite: "tile_wall", walkable: false },
  floor: { id: "floor", sprite: "tile_floor", walkable: true },
  roof: { id: "roof", sprite: "tile_roof", walkable: false },
  roof_slate: { id: "roof_slate", sprite: "tile_roof_slate", walkable: false },
  roof_violet: { id: "roof_violet", sprite: "tile_roof_violet", walkable: false },
  roof_awning: { id: "roof_awning", sprite: "tile_roof_awning", walkable: false },
  roof_moss: { id: "roof_moss", sprite: "tile_roof_moss", walkable: false },
  sign_goods: { id: "sign_goods", sprite: "sign_goods", walkable: false },
  sign_smith: { id: "sign_smith", sprite: "sign_smith", walkable: false },
  sign_potion: { id: "sign_potion", sprite: "sign_potion", walkable: false },
  sign_inn: { id: "sign_inn", sprite: "sign_inn", walkable: false },
  fence: { id: "fence", sprite: "tile_fence", walkable: false },
  flowers: { id: "flowers", sprite: "tile_flowers", walkable: true },
  barrel: { id: "barrel", sprite: "tile_barrel", walkable: false },
  crate: { id: "crate", sprite: "tile_crate", walkable: false },
  well: { id: "well", sprite: "tile_well", walkable: false },
  lamp: { id: "lamp", sprite: "tile_lamp", walkable: false },
  anvil: { id: "anvil", sprite: "tile_anvil", walkable: false },
  forge: { id: "forge", sprite: "tile_forge", walkable: false },
  shelf: { id: "shelf", sprite: "tile_shelf", walkable: false },
  cauldron: { id: "cauldron", sprite: "tile_cauldron", walkable: false },
  counter: { id: "counter", sprite: "tile_counter", walkable: false },
  bed: { id: "bed", sprite: "tile_bed", walkable: false },
  hearth: { id: "hearth", sprite: "tile_hearth", walkable: false },
  door: { id: "door", sprite: "tile_door", walkable: true },
  door_shut: { id: "door_shut", sprite: "tile_door_shut", walkable: false },
  cave: { id: "cave", sprite: "tile_cave", walkable: true },
  shrine: { id: "shrine", sprite: "tile_shrine", walkable: true },
};
