import { parseMap } from "../parseMap";
import type { WorldMap } from "../types";

/**
 * The frontier: two wild regions beyond the Ashenreach's mountain ring,
 * reached through passes in the east and west walls. Harder than anything
 * on the old overworld - late-game hunting grounds with their own forage.
 */
export const DEEPWOOD_MAP: WorldMap = parseMap(
  "deepwood",
  `
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ^^ffffffffffff........ffffffffffffffffffffffffffffffffffff^^
  ^^ffffffffffff........ffffffffffffffffffffffffffffffffffff^^
  ^^ffffff....ffffffffff....ffffffffffff....ffffffffffffffff^^
  ^^ffffff....ffffffffff....ffffffffffff....ffffffffffffffff^^
  ^^ffff..~~~~~~ffff..ffffffff..ffffffffff..ffffffffffffffff^^
  ^^ffff..~~~~~~ffff..ffffffff..ffffffffff..ffffffffffffffff^^
  ^^ffff~~~~~~~~~~ff....ffffff..ffff............ffffffffffff^^
  ^^ffff~~~~~~~~~~ff....ffffff..ffff............ffffffffffff^^
  ^^ffff~~~~~~~~~~ffff..ffff....ffff..ffffffff..ffffffffffff^^
  ^^ffff~~~~~~~~~~ffff..ffff....ffff..ffffffff..ffffffffffff^^
  ^^ffffff~~~~~~ffff....ff..ffffff..ffffffffff..ffffffffffff^^
  ^^ffffff~~~~~~ffff....ff..ffffff..ffffffffff..ffffffffffff^^
  ^^ffffffff..ffff....ffff..ffff....ffffff......ffffffffffff^^
  ^^ffffffff..ffff....ffff..ffff....ffffff......ffffffffffff^^
  ^^ffff..........ffff..ff....ff..ffffffff..ffffffffffffffff^^
  ^^ffff..........ffff..ff....ff..ffffffff..ffffffffffffffff^^
  ^^ffff..ffffffff..ffff..................ffffff....ffffffff^^
  ^^ffff..ffffffff..ffff..................ffffff....ffffffff^^
  ^^ff....ffffff..ffff......................ffff..ffffffffff^^
  ^^ff....ffffff..ffff......................ffff..ffffffffff^^
  ^^ff..ffff....ffff........ffffffffff........ffff..ffffffff^^
  ^^ff..ffff....ffff........ffffffffff........ffff..ffffffff^^
  C=========================....W.......==========..ffffffff^^
  ^=========================............==========..ffffffff^^
  ^^ff..ffff....ffffff......................ffffff..ffffffff^^
  ^^ff..ffff....ffffff......................ffffff..ffffffff^^
  ^^ffff..ffffff..ffff......................ffff..ffffffffff^^
  ^^ffff..ffffff..ffff......................ffff..ffffffffff^^
  ^^ffffff..ffff....ffffff..............ffffff....ffffffffff^^
  ^^ffffff..ffff....ffffff..............ffffff....ffffffffff^^
  ^^ffff....ffffffffff..ff..########__########....ffffffffff^^
  ^^ffff....ffffffffff..ff..########__########....ffffffffff^^
  ^^ff..ffffffff....ffff....##____________##..ffff..ffffffff^^
  ^^ff..ffffffff....ffff....##____________##..ffff..ffffffff^^
  ^^ffff..ffff..ffffffff....##____$_______##....ffffffffffff^^
  ^^ffff..ffff..ffffffff....##____________##....ffffffffffff^^
  ^^ffffff......ffffffff....##____________##..ffffffffffffff^^
  ^^ffffff......ffffffff....##____________##..ffffffffffffff^^
  ^^ffffffff..ffffffffffff..######____######....ffffffffffff^^
  ^^ffffffff..ffffffffffff..######____######....ffffffffffff^^
  ^^ffff..ffffffffffff..ffff......ffff....ffff..ffffffffffff^^
  ^^ffff..ffffffffffff..ffff......ffff....ffff..ffffffffffff^^
  ^^ffffffffffff....ffffffffffffffff....ffffffffffffffffffff^^
  ^^ffffffffffff....ffffffffffffffff....ffffffffffffffffffff^^
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  `,
  [{ x: 0, y: 24, to: { kind: "map", mapId: "overworld", x: 92, y: 32 } }],
  {
    grid: `
  ------------------------------------------------------------
  ------------------------------------------------------------
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  --DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD--
  ------------------------------------------------------------
  ------------------------------------------------------------
  `,
    legend: { D: "deepwood" },
  },
);

export const MIREFEN_MAP: WorldMap = parseMap(
  "mirefen",
  `
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ^^..wwwwwwwwwwwwww~~~~wwwwwwwwwwwwwwwwwwwwww..wwwwwwwwwwww^^
  ^^..wwwwwwwwwwwwww~~~~wwwwwwwwwwwwwwwwwwwwww..wwwwwwwwwwww^^
  ^^wwww..wwwwwwww~~~~~~~~wwwwww....wwwwwwwwwwww..wwwwwwwwww^^
  ^^wwww..wwwwwwww~~~~~~~~wwwwww....wwwwwwwwwwww..wwwwwwwwww^^
  ^^wwwwww..wwww~~~~~~~~~~~~wwww..ww..wwwwwwwwww..wwwwwwwwww^^
  ^^wwwwww..wwww~~~~~~~~~~~~wwww..ww..wwwwwwwwww..wwwwwwwwww^^
  ^^wwww..wwww..ww~~~~~~~~wwww..wwwwww..wwwwwwwwww..wwwwwwww^^
  ^^wwww..wwww..ww~~~~~~~~wwww..wwwwww..wwwwwwwwww..wwwwwwww^^
  ^^ww..wwwwww..wwww~~~~wwww..wwwwwwwwww..########..wwwwwwww^^
  ^^ww..wwwwww..wwww~~~~wwww..wwwwwwwwww..########..wwwwwwww^^
  ^^wwww..wwww..wwww~~bbwwww..wwww..wwww..##__W###..wwwwwwww^^
  ^^wwww..wwww..wwww~~bbwwww..wwww..wwww..##___###..wwwwwwww^^
  ^^wwwwww..ww..wwww~~bb..ww..ww..wwwwww..##____##..wwwwwwww^^
  ^^wwwwww..ww..wwww~~bb..ww..ww..wwwwww..##____##..wwwwwwww^^
  ^^wwww..wwwwwwww~~~~bb~~~~ww..wwww..ww..####__##..wwwwwwww^^
  ^^wwww..wwwwwwww~~~~bb~~~~ww..wwww..ww..####__##..wwwwwwww^^
  ^^ww..wwww..wwww~~~~~~~~~~wwww..wwwwwwww....ww....wwwwwwww^^
  ^^ww..wwww..wwww~~~~~~~~~~wwww..wwwwwwww....ww....wwwwwwww^^
  ^^wwww..wwwwwwwwww~~~~~~~~wwwwww..wwwwwwww..wwwwwwwwwwwwww^^
  ^^wwww..wwwwwwwwww~~~~~~~~wwwwww..wwwwwwww..wwwwwwwwwwwwww^^
  ^^wwwwww..wwwwwwwwww~~~~~~wwwwwwww..wwwwwwwwwwwwwwwwwwwwww^^
  ^^wwwwww..wwwwwwwwww~~~~~~wwwwwwww..wwwwwwwwwwwwwwwwwwwwww^^
  ^^..wwwwww..==============bb==================..*=========C=
  ^^..wwwwww..==============bb==================..w=========^=
  ^^wwww..wwwwwwwwww~~~~~~wwwwwwwwww..wwwwwwwwww..wwwwwwwwww^^
  ^^wwww..wwwwwwwwww~~~~~~wwwwwwwwww..wwwwwwwwww..wwwwwwwwww^^
  ^^ww..wwwwwwww..ww~~~~~~~~wwww..wwwwwwww..wwwwwwwwwwwwwwww^^
  ^^ww..wwwwwwww..ww~~~~~~~~wwww..wwwwwwww..wwwwwwwwwwwwwwww^^
  ^^wwww..wwww..wwww~~~~~~~~~~wwww..wwwwwwwwww..wwwwwwwwwwww^^
  ^^wwww..wwww..wwww~~~~~~~~~~wwww..wwwwwwwwww..wwwwwwwwwwww^^
  ^^wwwwww..wwwwwwww~~~~bb~~~~wwwwww..wwww..wwwwwwwwwwwwwwww^^
  ^^wwwwww..wwwwwwww~~~~bb~~~~wwwwww..wwww..wwwwwwwwwwwwwwww^^
  ^^wwww..wwwwwwwwww~~~~bb~~wwwwww..wwwwwwww..wwwwwwwwwwwwww^^
  ^^wwww..wwwwwwwwww~~~~bb~~wwwwww..wwwwwwww..wwwwwwwwwwwwww^^
  ^^ww..wwww..wwwwww~~~~bb~~~~wwww..wwww..wwwwwwww..wwwwwwww^^
  ^^ww..wwww..wwwwww~~~~bb~~~~wwww..wwww..wwwwwwww..wwwwwwww^^
  ^^wwww..wwwwwwww~~~~~~~~~~~~wwwwww..wwwwwwww..wwwwwwwwwwww^^
  ^^wwww..wwwwwwww~~~~~~~~~~~~wwwwww..wwwwwwww..wwwwwwwwwwww^^
  ^^wwwwww..wwww~~~~~~~~~~~~~~~~wwww..wwwwwwwwwwww..wwwwwwww^^
  ^^wwwwww..wwww~~~~~~~~~~~~~~~~wwww..wwwwwwwwwwww..wwwwwwww^^
  ^^wwww..wwwwww..~~~~~~~~~~~~wwwwww..wwww..wwwwwwwwwwwwwwww^^
  ^^wwww..wwwwww..~~~~~~~~~~~~wwwwww..wwww..wwwwwwwwwwwwwwww^^
  ^^wwwwwwww..wwwwww~~~~~~wwwwww..wwwwwwww..wwwwwwwwwwwwwwww^^
  ^^wwwwwwww..wwwwww~~~~~~wwwwww..wwwwwwww..wwwwwwwwwwwwwwww^^
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  `,
  [{ x: 58, y: 24, to: { kind: "map", mapId: "overworld", x: 2, y: 32 } }],
  {
    grid: `
  ------------------------------------------------------------
  ------------------------------------------------------------
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  --MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM--
  ------------------------------------------------------------
  ------------------------------------------------------------
  `,
    legend: { M: "mire" },
  },
);
