/**
 * Generates the game's pixel-art sprites as real PNG files (no dependencies,
 * hand-rolled PNG encoder on top of node:zlib). Run: node scripts/generate-sprites.mjs
 * Outputs 16x16 PNGs to public/sprites/ and a x8 preview sheet to scripts/preview.png
 */
import { deflateSync } from "node:zlib";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "public", "sprites");
mkdirSync(OUT, { recursive: true });

function crc32(buf) {
  let crc = ~0;
  for (let n = 0; n < buf.length; n++) {
    crc ^= buf[n];
    for (let k = 0; k < 8; k++) crc = crc & 1 ? (crc >>> 1) ^ 0xedb88320 : crc >>> 1;
  }
  return ~crc >>> 0;
}

function chunk(type, data) {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, "ascii"), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([len, body, crc]);
}

function encodePng(width, height, rgba) {
  const sig = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // color type RGBA
  const raw = Buffer.alloc(height * (1 + width * 4));
  for (let y = 0; y < height; y++) {
    raw[y * (1 + width * 4)] = 0; // filter: none
    rgba.copy(raw, y * (1 + width * 4) + 1, y * width * 4, (y + 1) * width * 4);
  }
  return Buffer.concat([sig, chunk("IHDR", ihdr), chunk("IDAT", deflateSync(raw)), chunk("IEND", Buffer.alloc(0))]);
}

function hexToRgba(hex) {
  const n = parseInt(hex.slice(1), 16);
  return [(n >> 16) & 0xff, (n >> 8) & 0xff, n & 0xff, 255];
}

function renderSprite(rows, palette, scale = 1) {
  const h = rows.length,
    w = rows[0].length;
  const buf = Buffer.alloc(w * scale * h * scale * 4);
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const ch = rows[y][x];
      if (ch === ".") continue;
      const hex = palette[ch];
      if (!hex) throw new Error(`Unknown palette char "${ch}" at ${x},${y}`);
      const [r, g, b, a] = hexToRgba(hex);
      for (let sy = 0; sy < scale; sy++) {
        for (let sx = 0; sx < scale; sx++) {
          const i = ((y * scale + sy) * w * scale + x * scale + sx) * 4;
          buf[i] = r;
          buf[i + 1] = g;
          buf[i + 2] = b;
          buf[i + 3] = a;
        }
      }
    }
  }
  return { buf, w: w * scale, h: h * scale };
}

const SKIN = "#e8b88a";

/** One shingle pattern, many buildings: roof variants swap palettes only. */
// Brick-laid shingle courses: a lit top edge per shingle, dark seams between,
// alternate rows offset half a shingle so roofs read as built, not painted.
const ROOF_ROWS = [
  "LLLRLLLRLLLRLLLR",
  "RRRDRRRDRRRDRRRD",
  "RRRDRRRDRRRDRRRD",
  "DDDDDDDDDDDDDDDD",
  "LRLLLRLLLRLLLRLL",
  "RDRRRDRRRDRRRDRR",
  "RDRRRDRRRDRRRDRR",
  "DDDDDDDDDDDDDDDD",
  "LLLRLLLRLLLRLLLR",
  "RRRDRRRDRRRDRRRD",
  "RRRDRRRDRRRDRRRD",
  "DDDDDDDDDDDDDDDD",
  "LRLLLRLLLRLLLRLL",
  "RDRRRDRRRDRRRDRR",
  "RDRRRDRRRDRRRDRR",
  "DDDDDDDDDDDDDDDD",
];

/**
 * A hanging placard against a building facade: T is the facade color, K the
 * chains, B the frame, and each icon row is 9 chars of plank-or-icon.
 */
const signRows = (icon) => [
  "TTTTTTTTTTTTTTTT",
  "TTTTTTTKKTTTTTTT",
  "TTTTTTTKKTTTTTTT",
  "TTTBBBBBBBBBBBTT",
  `TTTB${icon[0]}BTT`,
  `TTTB${icon[1]}BTT`,
  `TTTB${icon[2]}BTT`,
  `TTTB${icon[3]}BTT`,
  `TTTB${icon[4]}BTT`,
  "TTTBBBBBBBBBBBTT",
  "TTTTTTTTTTTTTTTT",
  "TTTTTTTTTTTTTTTT",
  "TTTTTTTTTTTTTTTT",
  "TTTTTTTTTTTTTTTT",
  "TTTTTTTTTTTTTTTT",
  "TTTTTTTTTTTTTTTT",
];

const sprites = {
  // ---------------- terrain tiles (must tile seamlessly) ----------------
  tile_grass: {
    palette: { G: "#3d7a35", L: "#4a8f40", D: "#35682e", Y: "#5aa04a" },
    rows: [
      "GGGGGGGGDDGGGGGG",
      "GGYGGGGGDGGGLGGG",
      "GGLGGGGGGGGGLGGG",
      "GGLGDDGGGGGGGGGG",
      "GGGGDDGGYGGGGGGG",
      "GDGGGGGGLGGGGDDG",
      "GGGGGGGGLGGGGDGG",
      "GGGGGYGGGGGGGGGG",
      "GGGGGLGGGDDGGGGG",
      "GGGGGLGGGDGGGGGG",
      "GGYGGGGGGGGGGGGG",
      "GGLGGGGGGGGGYGGG",
      "GGGGGGDDGGGGLGGG",
      "GGGGGGDDGGGGLGGG",
      "GDGGGGGGGGGGGGGG",
      "GLGGGGGGGGYGGGGG",
    ],
  },
  tile_grass2: {
    palette: { G: "#3d7a35", L: "#4a8f40", D: "#35682e", Y: "#5aa04a" },
    rows: [
      "GGGGLGGGGGGGGGGG",
      "GGLGGGGGGGLGGGGG",
      "GGGGGGGDDGGGGGGG",
      "GGGGGGGDDGGGLGGG",
      "GLGGGGGGGGGGGGGG",
      "GGGGGLGGGGGGGGLG",
      "GGGGGGGGGGGGGGGG",
      "GGGLGGGGGGLGGGGG",
      "GGGGGGGGGGGGGGGG",
      "GGGGGGLGGGGGGGGG",
      "GGDDGGGGGGGGGLGG",
      "GGDDGGGGLGGGGGGG",
      "GGGGGGGGGGGGGGGG",
      "GLGGGGGGGGGGLGGG",
      "GGGGGGLGGGGGGGGG",
      "GGGGGGGGGGGGGGGG",
    ],
  },
  tile_grass3: {
    palette: { G: "#3d7a35", L: "#4a8f40", S: "#7d8266", D: "#6a6f57" },
    rows: [
      "GGGGGGGGGGGGGGGG",
      "GGGGGGGGGGGGLGGG",
      "GGGGGGGGGGGGGGGG",
      "GGGSSGGGGGGGGGGG",
      "GGGSDGGGGGGGGGGG",
      "GGGGGGGGGGGGGGGG",
      "GGGGGGGGGGSGGGGG",
      "GGLGGGGGGGGGGGGG",
      "GGGGGGGGGGGGGGGG",
      "GGGGGGGGGGGGGGGG",
      "GGGGGGGGGGGGSSGG",
      "GGGGGLGGGGGGSDGG",
      "GGGGGGGGGGGGGGGG",
      "GGGGGGGGGGGGGGGG",
      "GGGGGGGLGGGGGGGG",
      "GGGGGGGGGGGGGGGG",
    ],
  },
  overlay_path_edge: {
    palette: { G: "#3d7a35", L: "#4a8f40" },
    rows: [
      "GGGGGGGGGGGGGGGG",
      "GG.GGG.GGGG.GGG.",
      ".G..G...GL...G..",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  tile_forest: {
    palette: { G: "#3d7a35", D: "#1f4a1a", T: "#2a5f24", H: "#38762c", B: "#4f371f", S: "#2c5726" },
    rows: [
      "GGGGHHTGGGGGGGGG",
      "GGGHHTTTTGGGHTGG",
      "GGHHTTTTTTGHHTTG",
      "GGHTTTTDTTGHTTDG",
      "GGHTTDTTTTGTTTTG",
      "GGTTTTTTDTGGTDGG",
      "GGGTTDTTTGGGGBGG",
      "GGGGTTTDTGGGSSGG",
      "GGGGGBBGGGGGGGGG",
      "GGGGSBBSGGHHTGGG",
      "GGGGGSSGGHHTTTGG",
      "GGHTGGGGGHTTTDTG",
      "GHHTTGGGGTTDTTTG",
      "GHTTDTGGGTTTTTGG",
      "GGTTTGGGGGTBTGGG",
      "GGGBGGGGGGSBSGGG",
    ],
  },
  tile_mountain: {
    palette: { S: "#6b6f7a", D: "#4a4e58", W: "#8a8f9a", K: "#33363e" },
    rows: [
      "SSSSSSSWSSSSSSSS",
      "SSSSSSWWWSSSSSSS",
      "SSSSSWWSWWSSSSSS",
      "SSSSWWSSSWWSSSSS",
      "SSSWWSSSSSWWSSSS",
      "SSWWSSSDDSSWWSSS",
      "SWWSSSDDDDSSWWSS",
      "WWSSSDDSSDDSSWWS",
      "SSSSDDSSSSDDSSSS",
      "SSSDDSSSSSSDDSSS",
      "SSDDSSSWSSSSDDSS",
      "SDDSSSWWWSSSSDDS",
      "DDSSSWWSWWSSSSDD",
      "DSSSWWSSSWWSSSSD",
      "KSSWWSSSSSWWSSSK",
      "KKKKKKKKKKKKKKKK",
    ],
  },
  tile_water: {
    palette: { B: "#2a4f8f", L: "#3d6bb8", W: "#5a8fd8", D: "#22417a", F: "#a8ccf0" },
    rows: [
      "BBBBDDBBBBBBBBBB",
      "BBLWWLBBBBDDDBBB",
      "BBBLLBBBBBBDBBBB",
      "BDBBBBBBLWWLBBBB",
      "BDDBBBBBBLLBBBBB",
      "BLWWLBBBBBBBBDDB",
      "BBLLFBBBLWWLBBBB",
      "BBBBBBBBBLLBBBBB",
      "BBBBBDDBBBBBBBBB",
      "BBBLWWLBBBBBBLWB",
      "BBBBLLBBBBDBBBLB",
      "BDDBBBBBBBDDBBBB",
      "BLWLBBBBBLWWLFBB",
      "BBLBBBBBBBLLBBBB",
      "BBBBBBDDBBBBBBBB",
      "BBBBBLWWLBBBBDBB",
    ],
  },
  tile_path: {
    palette: { P: "#b89a6a", H: "#c9ab77", D: "#a0855a", S: "#8f7550" },
    rows: [
      "PHHDPPHHHDPHHHDP",
      "PHDDPPHDDDPHDDDP",
      "SSSSPSSSSSPSSSSP",
      "PPPPPPPPPPPPPPPP",
      "HHDPHHHDPPHHDPHH",
      "HDDPHDDDPPHDDPHD",
      "SSSPSSSSPPSSSPSS",
      "PPPPPPPPPPPPPPPP",
      "PHHHDPHHDPPHHHDP",
      "PHDDDPHDDPPHDDDP",
      "PSSSSPSSSPPSSSSP",
      "PPPPPPPPPPPPPPPP",
      "HHDPPHHHDPHHDPPH",
      "HDDPPHDDDPHDDPPH",
      "SSSPPSSSSPSSSPPS",
      "PPPPPPPPPPPPPPPP",
    ],
  },
  tile_wall: {
    palette: { S: "#7a7268", D: "#57504a", M: "#454039" },
    rows: [
      "SSSSSSSMSSSSSSSM",
      "SDSSSDSMSDSSSDSM",
      "SSSSSSSMSSSSSSSM",
      "MMMMMMMMMMMMMMMM",
      "SSSMSSSSSSSMSSSS",
      "SDSMSDSSSDSMSDSS",
      "SSSMSSSSSSSMSSSS",
      "MMMMMMMMMMMMMMMM",
      "SSSSSSSMSSSSSSSM",
      "SDSSSDSMSDSSSDSM",
      "SSSSSSSMSSSSSSSM",
      "MMMMMMMMMMMMMMMM",
      "SSSMSSSSSSSMSSSS",
      "SDSMSDSSSDSMSDSS",
      "SSSMSSSSSSSMSSSS",
      "MMMMMMMMMMMMMMMM",
    ],
  },
  tile_door_shut: {
    palette: { S: "#7a7268", M: "#454039", B: "#6b4a2b", D: "#4f371f", P: "#8a6238" },
    rows: [
      "SSSSSSSSSSSSSSSS",
      "SSSMMMMMMMMMMSSS",
      "SSMBBBBBBBBBBMSS",
      "SSMBDBBBBBBDBMSS",
      "SSMPPPPPPPPPPMSS",
      "SSMBBDBBBBDBBMSS",
      "SSMBBBBBBBBBBMSS",
      "SSMBBBBBBBBBBMSS",
      "SSMPPPPPPPPPPMSS",
      "SSMBDBBBBBBDBMSS",
      "SSMBBBBBBBBBBMSS",
      "SSMBBDBBBBBBBMSS",
      "SSMPPPPPPPPPPMSS",
      "SSMBBBBBBBDBBMSS",
      "SSMBBBBBBBBBBMSS",
      "SSMBBBBBBBBBBMSS",
    ],
  },
  tile_door: {
    palette: { S: "#7a7268", M: "#454039", B: "#6b4a2b", D: "#4f371f", Y: "#e8c34a" },
    rows: [
      "SSSSSSSSSSSSSSSS",
      "SSSMMMMMMMMMMSSS",
      "SSMBBBBBBBBBBMSS",
      "SSMBDBBBBBBDBMSS",
      "SSMBBBBBBBBBBMSS",
      "SSMBBDBBBBDBBMSS",
      "SSMBBBBBBBBBBMSS",
      "SSMBBBBBBBBBBMSS",
      "SSMBDBBBBBBDBMSS",
      "SSMBBBBBYYBBBMSS",
      "SSMBBBBBYYBBBMSS",
      "SSMBBDBBBBBBBMSS",
      "SSMBBBBBBBDBBMSS",
      "SSMBBBBBBBBBBMSS",
      "SSMBBBBBBBBBBMSS",
      "SSMBBBBBBBBBBMSS",
    ],
  },
  tile_sand: {
    palette: { S: "#d8c088", D: "#c0a870", L: "#e8d4a0" },
    rows: [
      "SSSSSSSSSSSSSSSS",
      "SDDDSSSSSSLSSSSS",
      "SSSSDDSSSSSSSSSS",
      "SSSSSSSSSDDDSSSS",
      "SLSSSSSSSSSSDDSS",
      "SSSSSSSSSSSSSSSS",
      "SSSDDDSSSSSSSSLS",
      "SSSSSSDDSSSSSSSS",
      "SSLSSSSSSSDDDSSS",
      "SSSSSSSSSSSSSDDS",
      "SSSSSSSSSSSSSSSS",
      "SDDDSSSSLSSSSSSS",
      "SSSSDDSSSSSSSSSS",
      "SSSSSSSSSSSDDDSS",
      "SSLSSSSSSSSSSSDD",
      "SSSSSSSSSSSSSSSS",
    ],
  },
  tile_bridge: {
    palette: { B: "#8a5a2b", D: "#6b4520", W: "#2a4f8f", R: "#a06a35" },
    rows: [
      "WBBBBBBBBBBBBBBW",
      "WBRBBBBDBBBBBRBW",
      "WBBBBBBBBBBBBBBW",
      "WDDDDDDDDDDDDDDW",
      "WBBBBBBBBBBBBBBW",
      "WBBBDBBBBBRBBBBW",
      "WBBBBBBBBBBBBBBW",
      "WDDDDDDDDDDDDDDW",
      "WBBBBBBBBBBBBBBW",
      "WBRBBBBBDBBBBBBW",
      "WBBBBBBBBBBBBBBW",
      "WDDDDDDDDDDDDDDW",
      "WBBBBBBBBBBBBBBW",
      "WBBBBDBBBBBRBBBW",
      "WBBBBBBBBBBBBBBW",
      "WDDDDDDDDDDDDDDW",
    ],
  },
  tile_floor: {
    palette: { F: "#9a713d", D: "#7d5a30", L: "#b08548" },
    rows: [
      "FFFFFFFDFFFFFFFF",
      "FLFFFFFDFFFFLFFF",
      "FFFFFFFDFFFFFFFF",
      "DDDDDDDDDDDDDDDD",
      "FFFDFFFFFFFDFFFF",
      "FFFDFFLFFFFDFFFF",
      "FFFDFFFFFFFDFFFF",
      "DDDDDDDDDDDDDDDD",
      "FFFFFFFDFFFFFFFF",
      "FFLFFFFDFFFFFLFF",
      "FFFFFFFDFFFFFFFF",
      "DDDDDDDDDDDDDDDD",
      "FFFDFFFFFFFDFFFF",
      "FFFDFFFLFFFDFFFF",
      "FFFDFFFFFFFDFFFF",
      "DDDDDDDDDDDDDDDD",
    ],
  },
  tile_roof: {
    palette: { R: "#a03a3a", D: "#7d2a2a", L: "#b84a4a" },
    rows: ROOF_ROWS,
  },
  tile_roof_slate: {
    palette: { R: "#5a6578", D: "#454e60", L: "#6e7a90" },
    rows: ROOF_ROWS,
  },
  tile_roof_violet: {
    palette: { R: "#7a4a8f", D: "#603a70", L: "#8f5ea8" },
    rows: ROOF_ROWS,
  },
  tile_roof_moss: {
    palette: { R: "#6a7a3a", D: "#52602c", L: "#84965a" },
    rows: ROOF_ROWS,
  },
  tile_roof_awning: {
    palette: { A: "#3e8f5c", W: "#e8e0cc", D: "#2d6b44", w: "#b8b0a0" },
    rows: [
      "DDDDDDDDDDDDDDDD",
      "AAWWAAWWAAWWAAWW",
      "AAWWAAWWAAWWAAWW",
      "AAWWAAWWAAWWAAWW",
      "AAWWAAWWAAWWAAWW",
      "AAWWAAWWAAWWAAWW",
      "AAWWAAWWAAWWAAWW",
      "AAWWAAWWAAWWAAWW",
      "AAWWAAWWAAWWAAWW",
      "AAWWAAWWAAWWAAWW",
      "AAWWAAWWAAWWAAWW",
      "AAWWAAWWAAWWAAWW",
      "AAWWAAWWAAWWAAWW",
      "AAWWAAWWAAWWAAWW",
      "DDwwDDwwDDwwDDww",
      "DDwwDDwwDDwwDDww",
    ],
  },
  sign_goods: {
    palette: { T: "#3e8f5c", K: "#2a2118", B: "#4f371f", P: "#c9a86a", Y: "#e8c34a", O: "#b8912c" },
    rows: signRows(["PPPYYYPPP", "PPYYYYYPP", "PPYYOYYPP", "PPYYYYYPP", "PPPYYYPPP"]),
  },
  sign_smith: {
    palette: { T: "#5a6578", K: "#2a2118", B: "#4f371f", P: "#c9a86a", S: "#9aa0ac", H: "#8a6238" },
    rows: signRows(["PPSSSSSPP", "PPSSSSSPP", "PPPPHPPPP", "PPPPHPPPP", "PPPPHPPPP"]),
  },
  sign_potion: {
    palette: { T: "#7a4a8f", K: "#2a2118", B: "#4f371f", P: "#c9a86a", F: "#d85a8f", N: "#8a8f9a" },
    rows: signRows(["PPPPNPPPP", "PPPPFPPPP", "PPPFFFPPP", "PPFFFFFPP", "PPPFFFPPP"]),
  },
  sign_inn: {
    palette: { T: "#a03a3a", K: "#2a2118", B: "#4f371f", P: "#c9a86a", W: "#f5f0e0", M: "#d8a038" },
    rows: signRows(["PPWWWWWPP", "PPMMMMMPP", "PPMMMMMPP", "PPMMMMMPP", "PPPPPPPPP"]),
  },
  tile_fence: {
    palette: { G: "#3d7a35", L: "#4a8f40", W: "#9a7444", D: "#6b4a28" },
    rows: [
      "GGGGGGGGGGGGGGGG",
      "GGLGGGGGGGGGLGGG",
      "GGGGGGGGGGGGGGGG",
      "GGGGGGGLGGGGGGGG",
      "GGGGGGGGGGGGGGGG",
      "GWWGGGGWWGGGGWWG",
      "GWWGGGGWWGGGGWWG",
      "WWWWWWWWWWWWWWWW",
      "GWWGGGGWWGGGGWWG",
      "GWWGGGGWWGGGGWWG",
      "WWWWWWWWWWWWWWWW",
      "GWWGGGGWWGGGGWWG",
      "GDDGGGGDDGGGGDDG",
      "GGGGGGGGGGGGGGGG",
      "GGGGLGGGGGGGGGGG",
      "GGGGGGGGGGGGGGGG",
    ],
  },
  tile_flowers: {
    palette: { G: "#3d7a35", L: "#4a8f40", T: "#2a5f24", R: "#d84a4a", Y: "#e8c34a", W: "#f0f0e8" },
    rows: [
      "GGGGGGGGGGGGGGGG",
      "GGGGGGGGGGGGGGGG",
      "GGGRGGGGGGGGGGGG",
      "GGGTGGGGGGLGGGGG",
      "GGGGGGGGGGGGGGGG",
      "GGGGGGGGGGGYGGGG",
      "GGGGGGGGGGGTGGGG",
      "GGLGGGGGGGGGGGGG",
      "GGGGGGGGGGGGGGGG",
      "GGGGGGWGGGGGGGGG",
      "GGGGGGTGGGGGGGGG",
      "GGGGGGGGGGGGGLGG",
      "GGGGGGGGGGGGGRGG",
      "GGGGGGGGGGGGGTGG",
      "GGGGLGGGGGGGGGGG",
      "GGGGGGGGGGGGGGGG",
    ],
  },
  tile_barrel: {
    palette: { G: "#3d7a35", L: "#4a8f40", W: "#8a6238", D: "#6b4a28", M: "#555a64", T: "#a3814f" },
    rows: [
      "GGGGGGGGGGGGGGGG",
      "GGLGGGGGGGGGLGGG",
      "GGGGGGGGGGGGGGGG",
      "GGGGTTTTTTTTGGGG",
      "GGGDWWWWWWWWDGGG",
      "GGGMMMMMMMMMMGGG",
      "GGGDWWWDDWWWDGGG",
      "GGGDWWWDDWWWDGGG",
      "GGGMMMMMMMMMMGGG",
      "GGGDWWWDDWWWDGGG",
      "GGGDWWWDDWWWDGGG",
      "GGGMMMMMMMMMMGGG",
      "GGGGDDDDDDDDGGGG",
      "GGGGGGGGGGGGGGGG",
      "GGGGLGGGGGGGGGGG",
      "GGGGGGGGGGGGGGGG",
    ],
  },
  tile_crate: {
    palette: { G: "#3d7a35", L: "#4a8f40", P: "#a3814f", D: "#6b4a28" },
    rows: [
      "GGGGGGGGGGGGGGGG",
      "GGGGGGGGGGGGLGGG",
      "GGGGGGGGGGGGGGGG",
      "GGGGGGGGGGGGGGGG",
      "GGGDDDDDDDDDDGGG",
      "GGGDPPPPPPPPDGGG",
      "GGGDPDPPPPDPDGGG",
      "GGGDPPDPPDPPDGGG",
      "GGGDPPPDDPPPDGGG",
      "GGGDPPDPPDPPDGGG",
      "GGGDPDPPPPDPDGGG",
      "GGGDPPPPPPPPDGGG",
      "GGGDDDDDDDDDDGGG",
      "GGGGGGGGGGGGGGGG",
      "GGLGGGGGGGGGGGGG",
      "GGGGGGGGGGGGGGGG",
    ],
  },
  tile_well: {
    palette: { G: "#3d7a35", L: "#4a8f40", S: "#8a8f9a", d: "#5c6070", K: "#16181e", W: "#8a6238" },
    rows: [
      "GGGGGGGGGGGGGGGG",
      "GGGWGGGGGGGGWGGG",
      "GGGWWWWWWWWWWGGG",
      "GGGWGGGGGGGGWGGG",
      "GGGWGGKKGGGGWGGG",
      "GGGWGGGGGGGGWGGG",
      "GGGGSSSSSSSSGGGG",
      "GGGSSKKKKKKSSGGG",
      "GGGSKKKKKKKKSGGG",
      "GGGSKKKKKKKKSGGG",
      "GGGSSKKKKKKSSGGG",
      "GGGGSSSSSSSSGGGG",
      "GGGGddddddddGGGG",
      "GGGGGGGGGGGGGGGG",
      "GGGGLGGGGGGGLGGG",
      "GGGGGGGGGGGGGGGG",
    ],
  },
  tile_lamp: {
    palette: { G: "#3d7a35", L: "#4a8f40", K: "#2a2d35", F: "#454a55", Y: "#ffd469" },
    rows: [
      "GGGGGGGGGGGGGGGG",
      "GGGGGGGGGGGGGGGG",
      "GGGGGGGFFGGGGGGG",
      "GGGGGGFYYFGGGGGG",
      "GGGGGGFYYFGGGGGG",
      "GGGGGGFYYFGGGGGG",
      "GGGGGGGFFGGGGGGG",
      "GGGGGGGKKGGGGGGG",
      "GGGGGGGKKGGGGGGG",
      "GGGGGGGKKGGGGGGG",
      "GGGGGGGKKGGGGGGG",
      "GGGGGGGKKGGGGGGG",
      "GGGGGGGKKGGGGGGG",
      "GGGGGGKKKKGGGGGG",
      "GGGGGKKKKKKGGGGG",
      "GGGGGGGGGGGGGGGG",
    ],
  },
  helm: {
    palette: { S: "#8a8f9a", D: "#5c6070", K: "#2a2d35", R: "#a03a3a" },
    rows: [
      "................",
      "................",
      "................",
      "......RR........",
      "....SSSSSS......",
      "...SSSSSSSS.....",
      "..SSDDDDDDSS....",
      "..SDDDDDDDDS....",
      "..SDDDDDDDDS....",
      "..SDKKDDKKDS....",
      "..SDKKDDKKDS....",
      "..SSDDDDDDSS....",
      "...SSSSSSSS.....",
      "................",
      "................",
      "................",
    ],
  },
  gloves: {
    palette: { L: "#8a6238", D: "#5c3f24", S: "#b89a6a" },
    rows: [
      "................",
      "................",
      "................",
      "...LL....LL.....",
      "..LLLL..LLLL....",
      "..LSLL..LLSL....",
      "..LLLL..LLLL....",
      "..LLLL..LLLL....",
      "..DLLD..DLLD....",
      "..DLLD..DLLD....",
      "..DDDD..DDDD....",
      "...DD....DD.....",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  boots: {
    palette: { L: "#8a6238", D: "#5c3f24", K: "#2a2118" },
    rows: [
      "................",
      "................",
      "................",
      "...LL....LL.....",
      "...LL....LL.....",
      "...LL....LL.....",
      "...LL....LL.....",
      "...LL....LL.....",
      "..DLL...DLL.....",
      "..DLLL..DLLL....",
      "..DLLLL.DLLLL...",
      "..KKKKK.KKKKK...",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  amulet: {
    palette: { C: "#5c3f24", G: "#e8c34a", B: "#4ae6c8", K: "#2a2118" },
    rows: [
      "................",
      "................",
      "....CC..CC......",
      "...C......C.....",
      "...C......C.....",
      "...C......C.....",
      "....C....C......",
      ".....C..C.......",
      "......GG........",
      ".....GBBG.......",
      ".....GBBG.......",
      "......GG........",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  ring: {
    palette: { G: "#e8c34a", D: "#a8862a", B: "#4ae6c8" },
    rows: [
      "................",
      "................",
      "................",
      "................",
      "......BB........",
      ".....BBBB.......",
      "......BB........",
      ".....G..G.......",
      "....G....G......",
      "....G....G......",
      "....G....G......",
      "....DG..GD......",
      ".....DGGD.......",
      "................",
      "................",
      "................",
    ],
  },
  icon_speaker: {
    palette: { G: "#e8c34a", D: "#a8862a", W: "#f0e6c8" },
    rows: [
      "................",
      "................",
      "......G.........",
      ".....GG...W.....",
      "....GGG..W.W....",
      "..GGGGG.W.W.W...",
      "..GGGGG.W.W.W...",
      "..GGGGG.W.W.W...",
      "..GGGGG.W.W.W...",
      "..GGGGG.W.W.W...",
      "....GGG..W.W....",
      ".....GG...W.....",
      "......G.........",
      "................",
      "................",
      "................",
    ],
  },
  icon_speaker_off: {
    palette: { G: "#6b6f7a", D: "#4a4e58", R: "#c23b3b" },
    rows: [
      "................",
      "................",
      "......G.........",
      ".....GG.........",
      "....GGG..R...R..",
      "..GGGGG..RR.RR..",
      "..GGGGG...RRR...",
      "..GGGGG....R....",
      "..GGGGG...RRR...",
      "..GGGGG..RR.RR..",
      "....GGG..R...R..",
      ".....GG.........",
      "......G.........",
      "................",
      "................",
      "................",
    ],
  },
  icon_gear: {
    palette: { G: "#e8c34a", D: "#a8862a", K: "#2a2118" },
    rows: [
      "................",
      ".......GG.......",
      "...GG..GG..GG...",
      "....GGGGGGGG....",
      "....GGGGGGGG....",
      ".....GG..GG.....",
      "..GGGGG..GGGGG..",
      "..GGGGG..GGGGG..",
      ".....GG..GG.....",
      "....GGGGGGGG....",
      "....GGGGGGGG....",
      "...GG..GG..GG...",
      ".......GG.......",
      "................",
      "................",
      "................",
    ],
  },
  icon_anvil: {
    palette: { S: "#8a8f9a", D: "#5c6070", K: "#2a2d35" },
    rows: [
      "................",
      "................",
      "................",
      "..SSSSSSSSSS....",
      "..SDDDDDDDDS....",
      "...KDDDDDDK.....",
      ".....DDDD.......",
      ".....DDDD.......",
      "....SDDDDS......",
      "...SSDDDDSS.....",
      "..SSSSSSSSSS....",
      "..KKKKKKKKKK....",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  icon_cauldron: {
    palette: { K: "#2a2d35", D: "#454a55", G: "#4ec04e", L: "#8ae68a" },
    rows: [
      "................",
      "................",
      "....L..G..L.....",
      ".....G..L.......",
      "...KKKKKKKKK....",
      "..KGGGGGGGGGK...",
      "..KKKKKKKKKKK...",
      "..DKKKKKKKKKD...",
      "..DKKKKKKKKKD...",
      "...DKKKKKKKD....",
      "....KKKKKKK.....",
      "...KK.....KK....",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  chest_closed: {
    palette: { W: "#8a6238", D: "#5c3f24", G: "#e8c34a", K: "#2a2118" },
    rows: [
      "................",
      "................",
      "................",
      "................",
      "....WWWWWWWW....",
      "...WDDDDDDDDW...",
      "...WDDDDDDDDW...",
      "...WGGGGGGGGW...",
      "...WDDGKKGDDW...",
      "...WDDGKKGDDW...",
      "...WDDDDDDDDW...",
      "...WDDDDDDDDW...",
      "...WWWWWWWWWW...",
      "...KKKKKKKKKK...",
      "................",
      "................",
    ],
  },
  chest_open: {
    palette: { W: "#8a6238", D: "#5c3f24", G: "#e8c34a", Y: "#ffd469", K: "#2a2118" },
    rows: [
      "................",
      "....WWWWWWWW....",
      "...WDDDDDDDDW...",
      "...WDDDDDDDDW...",
      "...WWWWWWWWWW...",
      "...WYYYYYYYYW...",
      "...WYGGGGGGYW...",
      "...WGGGGGGGGW...",
      "...WDDDDDDDDW...",
      "...WDDGKKGDDW...",
      "...WDDDDDDDDW...",
      "...WDDDDDDDDW...",
      "...WWWWWWWWWW...",
      "...KKKKKKKKKK...",
      "................",
      "................",
    ],
  },
  road_glint: {
    palette: { G: "#e8c34a", Y: "#ffd469" },
    rows: [
      "................",
      "................",
      "................",
      "....Y...........",
      "...YGY..........",
      "....Y...........",
      "................",
      "..........Y.....",
      ".........YGY....",
      "..........Y.....",
      "................",
      "....Y...........",
      "...YGY.....Y....",
      "....Y.....YGY...",
      "...........Y....",
      "................",
    ],
  },
  herb_patch: {
    palette: { L: "#4a8f40", E: "#2a5f24", R: "#c8503a" },
    rows: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "....L....L......",
      "...LEL..LEL.....",
      "....L....L......",
      "..L....L....L...",
      ".LEL..LEL..LEL..",
      "..L....L....L...",
      "...R..R..R......",
      "..RR.RR..RR.....",
      "................",
      "................",
    ],
  },
  tile_cave: {
    palette: { S: "#6b6f7a", D: "#4a4e58", K: "#14151c", M: "#26282f" },
    rows: [
      "SSSSSSSSSSSSSSSS",
      "SSDSSSSSSSSSDSSS",
      "SSSSSDKKDSSSSSSS",
      "SSSSDKKKKDSSSSSS",
      "SSSDKKKKKKDSSSSS",
      "SSDKKKKKKKKDSSSS",
      "SSDKKKKKKKKDSSSS",
      "SDKKKKKKKKKKDSSS",
      "SDKKKKKKKKKKDSSS",
      "SDKMKKKKKKMKDSSS",
      "SDKKKKKKKKKKDSSS",
      "SDKKKKKKKKKKDSSS",
      "SDKKKKKKKKKKDSSS",
      "SDMKKKKKKKKMDSSS",
      "SDKKKKKKKKKKDSSS",
      "SSSSSSSSSSSSSSSS",
    ],
  },
  tile_marsh: {
    palette: { G: "#3d5a2c", W: "#2a4438", D: "#33492a", R: "#6b8a3d" },
    rows: [
      "GGGGGGGGGGGGGGGG",
      "GGWWWGGGGGGRGGGG",
      "GWWWWWGGGGGRGGGG",
      "GGWWWGGGGGGGGGGG",
      "GGGGGGGGDGGGGGGG",
      "GGGGGGGGGGGWWGGG",
      "GRGGGGGGGGWWWWGG",
      "GRGGGGDGGGWWWGGG",
      "GGGGGGGGGGGGGGGG",
      "GGGWWGGGGGGGGDGG",
      "GGWWWWGGGGRGGGGG",
      "GGGWWGGGGGRGGGGG",
      "GGGGGGGGGGGGGGGG",
      "GDGGGGGWWWGGGGGG",
      "GGGGGGWWWWWGGGGG",
      "GGGGGGGWWGGGGGGG",
    ],
  },
  tile_ash: {
    palette: { A: "#5a5650", D: "#454239", O: "#e87a2a", L: "#6b6760" },
    rows: [
      "AAAAAAAAAAAAAAAA",
      "AADAAAAAAAAALAAA",
      "AAAAAAAADAAAAAAA",
      "AAAAALAAAAAAAAAA",
      "AAAAAAAAAAAADAAA",
      "ADAAAAAAAAAAAAAA",
      "AAAAAAAOAAAAAAAA",
      "AAAAAAAAAAAAAALA",
      "AAALAAAAAADAAAAA",
      "AAAAAAAAAAAAAAAA",
      "AAAAAADAAAAAAAAA",
      "ALAAAAAAAAAAADAA",
      "AAAAAAAAALAAAAAA",
      "AAAADAAAAAAAAOAA",
      "AAAAAAAAAAAALAAA",
      "AADAAAAAAAAAAAAA",
    ],
  },
  // A grass bite out of a roof's outer corner: buildings stop being rectangles.
  overlay_roofcut: {
    palette: { G: "#3d7a35", K: "#2a2118" },
    rows: [
      "GGGGGGGG........",
      "GGGGGGK.........",
      "GGGGGK..........",
      "GGGGK...........",
      "GGGK............",
      "GGK.............",
      "GK..............",
      "GK..............",
      "K...............",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  // A chimney with a wisp, dropped on a hashed top-row roof tile.
  overlay_chimney: {
    palette: { S: "#6b6f7a", D: "#4a4e58", K: "#2a2d35", W: "#c8ccd8" },
    rows: [
      "..........W.....",
      ".........W......",
      "..........W.....",
      "........SSSS....",
      "........SDDS....",
      "........SDDS....",
      "........SDDS....",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  // Foam where water meets land; rotated onto each shore side at build time.
  overlay_shore: {
    palette: { F: "#a8ccf0", W: "#e8f4ff" },
    rows: [
      "FWFFFWFFWFFFWFFF",
      ".F..F..F...F..F.",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  // Transparent overlay marking wild (encounter-prone) terrain: sparse tufts.
  overlay_wild: {
    palette: { T: "#1f3318", D: "#2a1f14" },
    rows: [
      "................",
      "..T.............",
      "..T........T....",
      "...........T....",
      "................",
      "......T.........",
      "......T.......D.",
      "................",
      ".D..............",
      "............T...",
      "....T.......T...",
      "....T...........",
      "................",
      "..........D.....",
      "..T.............",
      "................",
    ],
  },
  tile_shrine: {
    palette: { G: "#3d7a35", S: "#8a8f9a", D: "#5c6070", W: "#4ae6c8", L: "#c8fff0" },
    rows: [
      "GGGGGGGGGGGGGGGG",
      "GGGGGGLGGGGGGGGG",
      "GGGGGLWLGGGGGGGG",
      "GGGGGGWGGGGGGGGG",
      "GGGGGSWSGGGGGGGG",
      "GGGGSSWSSGGGGGGG",
      "GGGGSWWWSGGGGGGG",
      "GGGGSSWSSGGGGGGG",
      "GGGGGSSSGGGGGGGG",
      "GGGGGSSSGGGGGGGG",
      "GGGGSSSSSGGGGGGG",
      "GGGSSSSSSSGGGGGG",
      "GGGSDSSSDSGGGGGG",
      "GGGSSSSSSSGGGGGG",
      "GGGGGGGGGGGGGGGG",
      "GGGGGGGGGGGGGGGG",
    ],
  },
  tile_anvil: {
    palette: { F: "#9a713d", L: "#b08548", S: "#555a64", K: "#3a3e46" },
    rows: [
      "FFFFFFFFFFFFFFFF",
      "FLFFFFFFFFFFLFFF",
      "FFFFFFFFFFFFFFFF",
      "FFSSSSSSSSSSFFFF",
      "FFFFKSSSSKFFFFFF",
      "FFFFFKSSKFFFFFFF",
      "FFFFKSSSSKFFFFFF",
      "FFFKSSSSSSKFFFFF",
      "FFFSSSSSSSSFFFFF",
      "FFFKKKKKKKKFFFFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFLFFF",
      "FFFFFFFFFFFFFFFF",
      "FLFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
    ],
  },
  tile_forge: {
    palette: { F: "#9a713d", S: "#6b6f7a", K: "#33363e", O: "#ff8c28", Y: "#ffd469" },
    rows: [
      "FFFFFFFFFFFFFFFF",
      "FFSSSSSSSSSSSSFF",
      "FSSSSSSSSSSSSSSF",
      "FSSKKKKKKKKKKSSF",
      "FSSKOYYOOYYOKSSF",
      "FSSKOOYYYYOOKSSF",
      "FSSKKKKKKKKKKSSF",
      "FSSSSSSSSSSSSSSF",
      "FFSSSSSSSSSSSSFF",
      "FFFKKKKKKKKKKFFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
    ],
  },
  tile_shelf: {
    palette: { F: "#9a713d", W: "#8a6238", D: "#6b4a28", R: "#d85a8f", B: "#3d6bb8", G: "#3e8f5c" },
    rows: [
      "FWWWWWWWWWWWWWWF",
      "FWRFBFGFRFBFGFWF",
      "FWWWWWWWWWWWWWWF",
      "FWBFGFRFBFGFRFWF",
      "FWWWWWWWWWWWWWWF",
      "FWGFRFBFGFRFBFWF",
      "FWWWWWWWWWWWWWWF",
      "FWFFDFFFFFDFFFWF",
      "FWFFDFFFFFDFFFWF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
    ],
  },
  tile_cauldron: {
    palette: { F: "#9a713d", K: "#2a2d35", G: "#7ddb6e", L: "#c8ffc0" },
    rows: [
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFLFFFFFFFFFF",
      "FFFFFGFFFGLFFFFF",
      "FFFKKKKKKKKKFFFF",
      "FFFKGGGGGGGKFFFF",
      "FFKKKKKKKKKKKFFF",
      "FFKKKKKKKKKKKFFF",
      "FFFKKKKKKKKKFFFF",
      "FFFFKFFFFFKFFFFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
      "FFLFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFLFFFF",
      "FFFFFFFFFFFFFFFF",
    ],
  },
  tile_counter: {
    palette: { F: "#9a713d", L: "#b08548", W: "#8a6238", D: "#6b4a28" },
    rows: [
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
      "LLLLLLLLLLLLLLLL",
      "WWWWWWWWWWWWWWWW",
      "WWWDWWWWWWWDWWWW",
      "WWWDWWWWWWWDWWWW",
      "WWWWWWWWWWWWWWWW",
      "DDDDDDDDDDDDDDDD",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
      "FFLFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFLFFFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
    ],
  },
  tile_bed: {
    palette: { F: "#9a713d", W: "#8a6238", P: "#f0ead8", B: "#3d6bb8" },
    rows: [
      "FFFFFFFFFFFFFFFF",
      "FFWWWWWWWWWWWWFF",
      "FFWPPPPPPPPPPWFF",
      "FFWPPPPPPPPPPWFF",
      "FFWBBBBBBBBBBWFF",
      "FFWBBBBBBBBBBWFF",
      "FFWBBBBBBBBBBWFF",
      "FFWBBBBBBBBBBWFF",
      "FFWBBBBBBBBBBWFF",
      "FFWBBBBBBBBBBWFF",
      "FFWBBBBBBBBBBWFF",
      "FFWWWWWWWWWWWWFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
    ],
  },
  tile_hearth: {
    palette: { F: "#9a713d", S: "#8a8f9a", K: "#33363e", O: "#ff8c28", Y: "#ffd469", D: "#7d5a30" },
    rows: [
      "FFFFFFFFFFFFFFFF",
      "FSSSSSSSSSSSSSSF",
      "FSKKKKKKKKKKKKSF",
      "FSKKKKKKKKKKKKSF",
      "FSKKKOYYYYOKKKSF",
      "FSKKOOYYYYOOKKSF",
      "FSKOOYYYYYYOOKSF",
      "FSSSSSSSSSSSSSSF",
      "FFDDDDDDDDDDDDFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFF",
    ],
  },
  // ---------------- heroes ----------------
  hero_warrior: {
    palette: {
      H: "#9aa5b1",
      D: "#5c6670",
      F: SKIN,
      K: "#22242b",
      B: "#7d8894",
      L: "#4a4f5a",
      O: "#8a5a2b",
      R: "#c23b3b",
    },
    rows: [
      "......RR........",
      ".....RRRR.......",
      "....HHHHHH......",
      "...HHHHHHHH.....",
      "...HFFFFFFH.....",
      "...HFKFFKFH.....",
      "...HFFFFFFH.....",
      "....FFFFFF......",
      "...BBBBBBBB.....",
      "..BBBBBBBBBB....",
      ".FBBBBBBBBBBF...",
      ".FBBOOOOOOBBF...",
      "..BBBBBBBBBB....",
      "...LLL..LLL.....",
      "...LLL..LLL.....",
      "...DD....DD.....",
    ],
  },
  hero_mage: {
    palette: {
      H: "#3b5bd6",
      D: "#26398f",
      F: SKIN,
      K: "#22242b",
      R: "#4a6be6",
      L: "#26398f",
      W: "#d8d0c0",
      Y: "#e8c34a",
    },
    rows: [
      ".......HH.......",
      "......HHHH......",
      ".....HHHHHH.....",
      "....HHHHHHHH....",
      "..HHHHHHHHHHHH..",
      "...WFFFFFFFFW...",
      "...WFKFFFFKW....",
      "...WFFFFFFFW....",
      "....WWWWWWW.....",
      "...RRRRRRRRR....",
      "..RRRRYYRRRRR...",
      ".FRRRRYYRRRRF...",
      "..RRRRRRRRRR....",
      "..RRRRRRRRRR....",
      "..LLLLLLLLLL....",
      "...DD....DD.....",
    ],
  },
  hero_rogue: {
    palette: { H: "#3a3f4a", D: "#23262e", F: SKIN, K: "#c23b3b", B: "#4a4f5a", L: "#2e323b", O: "#6b4a2b" },
    rows: [
      "................",
      ".....HHHHHH.....",
      "....HHHHHHHH....",
      "...HHHHHHHHHH...",
      "...HHFFFFFFHH...",
      "...HHFKFFKFHH...",
      "...HHHFFFFHHH...",
      "....HHHHHHHH....",
      "...BBBBBBBB.....",
      "..BBBBBBBBBB....",
      ".FBBBBBBBBBBF...",
      ".FBBOOOOOOBBF...",
      "..BBBBBBBBBB....",
      "...LLL..LLL.....",
      "...LLL..LLL.....",
      "...DD....DD.....",
    ],
  },
  hero_cleric: {
    palette: { H: "#e8e2d0", D: "#b8b0a0", F: SKIN, K: "#22242b", B: "#f0ead8", L: "#c8c0b0", Y: "#e8c34a" },
    rows: [
      ".......YY.......",
      ".....YYYYYY.....",
      "....HHHHHHHH....",
      "...HHHHHHHHHH...",
      "...HFFFFFFFFH...",
      "...HFKFFFFKFH...",
      "...HFFFFFFFFH...",
      "....FFFFFFFF....",
      "...BBBBBBBBBB...",
      "..BBBBYYBBBBB...",
      ".FBBBBYYBBBBBF..",
      ".FBBBYYYYBBBBF..",
      "..BBBBYYBBBBB...",
      "..BBBBBBBBBBB...",
      "..LLLLLLLLLLL...",
      "...DD.....DD....",
    ],
  },
  merchant: {
    palette: {
      H: "#8a5a2b",
      D: "#5f3d1c",
      F: SKIN,
      K: "#22242b",
      B: "#6b4a2b",
      A: "#c8a878",
      L: "#4f371f",
      Y: "#e8c34a",
    },
    rows: [
      "................",
      ".....HHHHHH.....",
      "....HHHHHHHH....",
      "...HHFFFFFFHH...",
      "...HHFKFFKFHH...",
      "...HHFFFFFFHH...",
      "....HFFFFFFH....",
      "....BBBBBBBB....",
      "...BBAAAAAABB...",
      "..FBBAAAAAABBF..",
      "..YBBAAAAAABBF..",
      "..YYBAAAAAABB...",
      "...BBBBBBBBBB...",
      "...LLL....LLL...",
      "...LLL....LLL...",
      "...DD......DD...",
    ],
  },
  villager: {
    palette: { H: "#6b4a2b", F: SKIN, K: "#22242b", B: "#5a7a8f", L: "#3d5666", D: "#2e3d47" },
    rows: [
      "................",
      ".....HHHHHH.....",
      "....HHHHHHHH....",
      "...HFFFFFFFFH...",
      "...HFKFFFFKFH...",
      "...HFFFFFFFFH...",
      "....FFFFFFFF....",
      "....BBBBBBBB....",
      "...BBBBBBBBBB...",
      "..FBBBBBBBBBBF..",
      "..FBBBBBBBBBBF..",
      "...BBBBBBBBBB...",
      "...LLL....LLL...",
      "...LLL....LLL...",
      "...DD......DD...",
      "................",
    ],
  },
  villager_woman: {
    palette: { H: "#8f5a2b", F: SKIN, K: "#22242b", B: "#a84a5f", L: "#7d3547", D: "#5c2735" },
    rows: [
      "................",
      "....HHHHHHHH....",
      "...HHHHHHHHHH...",
      "...HFFFFFFFFH...",
      "...HFKFFFFKFH...",
      "...HFFFFFFFFH...",
      "...HHFFFFFFHH...",
      "....BBBBBBBB....",
      "...BBBBBBBBBB...",
      "..FBBBBBBBBBBF..",
      "..FBBBBBBBBBBF..",
      "..BBBBBBBBBBBB..",
      "..BBBBBBBBBBBB..",
      "..LLLLLLLLLLLL..",
      "...DD......DD...",
      "................",
    ],
  },
  elder: {
    palette: {
      H: "#d8d4c8",
      F: SKIN,
      K: "#22242b",
      B: "#6b5a8f",
      L: "#4a3d66",
      D: "#352c4a",
      W: "#b8b4a8",
      S: "#8a5a2b",
    },
    rows: [
      "................",
      ".....HHHHHH.....",
      "....HHHHHHHH....",
      "...HFFFFFFFFH...",
      "...HFKFFFFKFH...",
      "...HFFFFFFFFH...",
      "....FWWWWWWF....",
      "....WWWWWWWW....",
      "....BBBBBBBBS...",
      "...BBBBBBBBBBS..",
      "..FBBBBBBBBBBS..",
      "..FBBBBBBBBBBS..",
      "..BBBBBBBBBBBS..",
      "..BBBBBBBBBBBS..",
      "..LLLLLLLLLLLS..",
      ".............S..",
    ],
  },
  innkeeper: {
    palette: { H: "#3d2c1f", F: SKIN, K: "#22242b", B: "#f0ead8", L: "#8f6a3d", D: "#5c4527", A: "#c8b89a" },
    rows: [
      "................",
      ".....HHHHHH.....",
      "....HHHHHHHH....",
      "...HFFFFFFFFH...",
      "...HFKFFFFKFH...",
      "...HFFFFFFFFH...",
      "....FFFFFFFF....",
      "....BBBBBBBB....",
      "...BAAAAAAAAB...",
      "..FBAAAAAAAABF..",
      "..FBAAAAAAAABF..",
      "...BAAAAAAAAB...",
      "...LLL....LLL...",
      "...LLL....LLL...",
      "...DD......DD...",
      "................",
    ],
  },
  smith: {
    palette: {
      H: "#8f3d2b",
      F: SKIN,
      K: "#22242b",
      B: "#5c6670",
      A: "#3a3f4a",
      L: "#4a4f5a",
      D: "#2e323b",
      O: "#e87a2a",
    },
    rows: [
      "................",
      ".....HHHHHH.....",
      "....HHHHHHHH....",
      "...HFFFFFFFFH...",
      "...HFKFFFFKFH...",
      "...HFFFFFFFFH...",
      "....FFFFFFFF....",
      "....BBBBBBBB....",
      "...BAAAAAAAAB...",
      "..FBAAAAAAAABF..",
      "..OBAAAAAAAABF..",
      "..OOAAAAAAAAB...",
      "...LLL....LLL...",
      "...LLL....LLL...",
      "...DD......DD...",
      "................",
    ],
  },
  alchemist: {
    palette: { H: "#3d6b4a", F: SKIN, K: "#22242b", B: "#4a8a5f", L: "#2e5c3d", D: "#1f4029", G: "#4ae6c8" },
    rows: [
      ".......HH.......",
      "......HHHH......",
      ".....HHHHHH.....",
      "....HHHHHHHH....",
      "..HHHHHHHHHHHH..",
      "...HFFFFFFFFH...",
      "...HFKFFFFKFH...",
      "...HFFFFFFFFH...",
      "....BBBBBBBB....",
      "...BBBGGBBBBB...",
      "..FBBBGGBBBBBF..",
      "..BBBBBBBBBBBB..",
      "..BBBBBBBBBBBB..",
      "..LLLLLLLLLLLL..",
      "...DD......DD...",
      "................",
    ],
  },
  // ---------------- monsters ----------------
  slime: {
    palette: { G: "#4ec04e", D: "#2e8a2e", W: "#ffffff", K: "#1a1a1a" },
    rows: [
      "................",
      "................",
      "................",
      "................",
      "......GGGG......",
      "....GGGGGGGG....",
      "...GGGGGGGGGG...",
      "..GGGGGGGGGGGG..",
      "..GWWGGGGGGWWG..",
      ".GGWKGGGGGGWKGG.",
      ".GGGGGGGGGGGGGG.",
      ".GGGGGKKKKGGGGG.",
      ".GGGGGGGGGGGGGG.",
      ".GDGGGGGGGGGGDG.",
      "..DDGGGGGGGGDD..",
      "...DDDDDDDDDD...",
    ],
  },
  goblin: {
    palette: { G: "#6aa84f", D: "#456f33", K: "#1a1a1a", R: "#c23b3b", B: "#6b4a2b", W: "#e8e2d0" },
    rows: [
      "................",
      "..G..........G..",
      ".GG..GGGGGG..GG.",
      ".GGGGGGGGGGGGGG.",
      "..GGGGGGGGGGGG..",
      "...GRRGGGGRRG...",
      "...GRKGGGGKRG...",
      "...GGGGGGGGGG...",
      "....GWGWGWGG....",
      ".....GGGGGG.....",
      "....BBBBBBBB....",
      "...BBBBBBBBBB...",
      "..GBBBBBBBBBBG..",
      "...BBBBBBBBBB...",
      "....GG....GG....",
      "...GGG....GGG...",
    ],
  },
  skeleton: {
    palette: { W: "#e8e4d8", D: "#b0aa98", K: "#1a1a1a" },
    rows: [
      "....WWWWWWWW....",
      "...WWWWWWWWWW...",
      "...WWWWWWWWWW...",
      "...WKKWWWWKKW...",
      "...WKKWWWWKKW...",
      "...WWWWKKWWWW...",
      "....WKWKWKWW....",
      "......WWWW......",
      "....WWWWWWWW....",
      "..WWWWWWWWWWWW..",
      ".WW.WWWWWWWW.WW.",
      ".W..WWWWWWWW..W.",
      ".W..WWWWWWWW..W.",
      "....WW....WW....",
      "....WW....WW....",
      "...WWW....WWW...",
    ],
  },
  wolf: {
    palette: { G: "#8a8f9a", D: "#5c6070", K: "#1a1a1a", R: "#c23b3b", W: "#e8e4d8" },
    rows: [
      "................",
      ".GG..........GG.",
      ".GGG........GGG.",
      ".GGGG......GGGG.",
      "..GGGGGGGGGGGG..",
      "..GGGGGGGGGGGG..",
      "..GKKGGGGGGKKG..",
      "..GRRGGGGGGRRG..",
      "...GGGGGGGGGG...",
      "...GGGDDDDGGG...",
      "....GGDDDDGG....",
      ".....GWWWWG.....",
      ".....GWKKWG.....",
      "......WWWW......",
      "......W..W......",
      "................",
    ],
  },
  orc: {
    palette: { G: "#4f7a3a", D: "#365427", K: "#1a1a1a", R: "#c23b3b", W: "#e8e2d0", B: "#5c4630" },
    rows: [
      "..GG........GG..",
      ".GGGGGGGGGGGGGG.",
      ".GGGGGGGGGGGGGG.",
      ".GGRRGGGGGGRRGG.",
      ".GGRKGGGGGGKRGG.",
      ".GGGGGGGGGGGGGG.",
      ".GGWGGGGGGGGWGG.",
      ".GGWGGGGGGGGWGG.",
      "..GGGGGGGGGGGG..",
      "...BBBBBBBBBB...",
      "..BBBBBBBBBBBB..",
      ".GBBBBBBBBBBBBG.",
      ".GBBBBBBBBBBBBG.",
      "..BBBBBBBBBBBB..",
      "...GGG....GGG...",
      "..GGGG....GGGG..",
    ],
  },
  ghost: {
    palette: { W: "#dfe6f0", D: "#aab6c8", K: "#1a1a2a" },
    rows: [
      "......WWWW......",
      "....WWWWWWWW....",
      "...WWWWWWWWWW...",
      "..WWWWWWWWWWWW..",
      "..WWKKWWWWKKWW..",
      "..WWKKWWWWKKWW..",
      "..WWWWWWWWWWWW..",
      "..WWWWWKKWWWWW..",
      "..WWWWWWWWWWWW..",
      "..WWWWWWWWWWWW..",
      "..WWWWWWWWWWWW..",
      "..WWWWWWWWWWWW..",
      "..WDWWDWWDWWDW..",
      "..W.WW.WW.WW.W..",
      "................",
      "................",
    ],
  },
  golem: {
    palette: { S: "#8a8478", D: "#5f5a50", K: "#e8c34a", M: "#3a362e" },
    rows: [
      "...SSSSSSSSSS...",
      "..SSSSSSSSSSSS..",
      "..SSKKSSSSKKSS..",
      "..SSKKSSSSKKSS..",
      "..SSSSSSSSSSSS..",
      "..SSSSMMMMSSSS..",
      "...SSSSSSSSSS...",
      ".SSSSSSSSSSSSSS.",
      ".SSDSSSSSSSSDSS.",
      ".SSDSSSDDSSSDSS.",
      ".SSDSSSDDSSSDSS.",
      ".SSSSSSSSSSSSSS.",
      "..SSSS....SSSS..",
      "..SSSS....SSSS..",
      "..SSSS....SSSS..",
      ".SSSSSS..SSSSSS.",
    ],
  },
  troll: {
    palette: { T: "#7a6a4f", D: "#544933", K: "#1a1a1a", R: "#c23b3b", W: "#e8e2d0", G: "#4f7a3a" },
    rows: [
      "...TTTTTTTTTT...",
      "..TTTTTTTTTTTT..",
      "..TTKKTTTTKKTT..",
      "..TTKRTTTTRKTT..",
      "..TTTTTTTTTTTT..",
      "..TTWTTTTTTWTT..",
      "...TTTTTTTTTT...",
      "..TTTTTTTTTTTT..",
      ".TTTTTTTTTTTTTT.",
      "TTTTTTTTTTTTTTTT",
      "TTTGGGGGGGGGGTTT",
      ".TTGGGGGGGGGGTT.",
      "..TTTTTTTTTTTT..",
      "...TTT....TTT...",
      "...TTT....TTT...",
      "..TTTT....TTTT..",
    ],
  },
  wyvern: {
    palette: { G: "#3f8a5f", D: "#2a5f40", K: "#1a1a1a", Y: "#e8c34a", W: "#e8e2d0" },
    rows: [
      "DD............DD",
      "DDD..........DDD",
      "DDDD.GGGGGG.DDDD",
      ".DDDGGGGGGGGDDD.",
      ".DDGGYKGGKYGGDD.",
      "..DGGGGGGGGGGD..",
      "..GGGGWWWWGGGG..",
      "...GGGGGGGGGG...",
      "....GGGGGGGG....",
      "...GGGGGGGGGG...",
      "..GGGGGGGGGGGG..",
      "..GGGGGGGGGGGG..",
      "...GGGGGGGGGG...",
      "....GG....GG....",
      "....GGG..GGG....",
      "......DDDD......",
    ],
  },
  dragon: {
    palette: { R: "#c23b3b", D: "#8a2525", K: "#1a1a1a", Y: "#e8c34a", W: "#e8e2d0", O: "#e87a2a" },
    rows: [
      "DD.....YY.....DD",
      "DDD...YYYY...DDD",
      "DDDD.RRRRRR.DDDD",
      ".DDDRRRRRRRRDDD.",
      ".DDRRYKRRKYRRDD.",
      "..DRRRRRRRRRRD..",
      "..RRRRWWWWRRRR..",
      "...RRRWWWWRRR...",
      "....RRRRRRRR....",
      "...RRROOOORRR...",
      "..RRRROOOORRRR..",
      "..RRRRRRRRRRRR..",
      ".RRRRRRRRRRRRRR.",
      "..RRR.RRRR.RRR..",
      "..RR...RR...RR..",
      ".DDD...DD...DDD.",
    ],
  },
  boneknight: {
    palette: { W: "#e8e4d8", A: "#4a4f5a", D: "#2e323b", R: "#c23b3b" },
    rows: [
      "....WWWWWWWW....",
      "...WWWWWWWWWW...",
      "...WRRWWWWRRW...",
      "...WRRWWWWRRW...",
      "...WWWWDDWWWW...",
      "....WDWDWDWW....",
      "...AAAAAAAAAA...",
      "..AAAAAAAAAAAA..",
      ".AAWAAAAAAAAWAA.",
      ".WAAAADDDDAAAAW.",
      ".WAAAADDDDAAAAW.",
      "..AAAAAAAAAAAA..",
      "...AAA....AAA...",
      "...AAA....AAA...",
      "...WW......WW...",
      "................",
    ],
  },
  shade: {
    palette: { S: "#3a3450", D: "#262138", W: "#c8c0ff" },
    rows: [
      "......SSSS......",
      "....SSSSSSSS....",
      "...SSSSSSSSSS...",
      "..SSSSSSSSSSSS..",
      "..SSWWSSSSWWSS..",
      "..SSWWSSSSWWSS..",
      "..SSSSSSSSSSSS..",
      "..SSSSSWWSSSSS..",
      "..SSSSSSSSSSSS..",
      "..SSSSSSSSSSSS..",
      "..SSSSSSSSSSSS..",
      "..SSSSSSSSSSSS..",
      "..SDSSDSSDSSDS..",
      "..S.SS.SS.SS.S..",
      "................",
      "................",
    ],
  },
  mimic: {
    palette: { B: "#8a5a2b", D: "#5f3d1c", G: "#e8c34a", W: "#f0ead8", T: "#c23b3b", K: "#1a0f08" },
    rows: [
      "................",
      "..BBBBBBBBBBBB..",
      ".BBBBBBBBBBBBBB.",
      ".BGGGGGGGGGGGGB.",
      ".BBBBBBBBBBBBBB.",
      ".BWWBWWBBWWBWWB.",
      ".KKKKKKKKKKKKKK.",
      ".KKKKKKKKKKKKKK.",
      ".KTTTTTTTTTTTTK.",
      ".BWWBWWBBWWBWWB.",
      ".BBBBBBBBBBBBBB.",
      ".BGGGGGGGGGGGGB.",
      ".BBBBBBBBBBBBBB.",
      "..BBBBBBBBBBBB..",
      "...GG......GG...",
      "................",
    ],
  },
  imp: {
    palette: { R: "#c23b3b", D: "#8a2525", K: "#1a1a1a", Y: "#e8c34a", W: "#e8e4d8" },
    rows: [
      "..W..........W..",
      "..WW........WW..",
      "...RRRRRRRRRR...",
      "..RRRRRRRRRRRR..",
      "..RYYRRRRRRYYR..",
      "..RYKRRRRRRKYR..",
      "..RRRRRRRRRRRR..",
      "...RRRWWWWRRR...",
      "....RRRRRRRR....",
      "...RRRRRRRRRR...",
      "..RRRRRRRRRRRR..",
      ".RRRRRRRRRRRRRR.",
      "..RRR.RRRR.RRR..",
      "..RR...RR...RR..",
      "..D....DD....D..",
      "................",
    ],
  },
  lich: {
    palette: { W: "#e8e4d8", G: "#4ae64a", C: "#e8c34a", P: "#4a2a6b", D: "#2e1a44", K: "#1a1a1a" },
    rows: [
      "...C.C.CC.C.C...",
      "...CCCCCCCCCC...",
      "...WWWWWWWWWW...",
      "..WWWWWWWWWWWW..",
      "..WGGWWWWWWGGW..",
      "..WGGWWWWWWGGW..",
      "..WWWWWDDWWWWW..",
      "...WWKWKKWKWW...",
      "....PPPPPPPP....",
      "...PPPPPPPPPP...",
      "..PPPPPPPPPPPP..",
      "..PPPDDDDDDPPP..",
      ".PPPPPPPPPPPPPP.",
      ".PPPPPPPPPPPPPP.",
      ".PPPPPPPPPPPPPP.",
      "..DDDDDDDDDDDD..",
    ],
  },
  // ---------------- status effects ----------------
  effect_poison: {
    palette: { G: "#4ec04e", D: "#2e8a2e", W: "#c8ffc8" },
    rows: [
      "................",
      "................",
      ".......GG.......",
      ".......GG.......",
      "......GGGG......",
      "......GGGG......",
      ".....GGGGGG.....",
      "....GGGGGGGG....",
      "...GGGGGGGGGG...",
      "...GWGGGGGGGG...",
      "...GWWGGGGGGG...",
      "...GGWGGGGGDG...",
      "....GGGGGGDD....",
      ".....GGGGDD.....",
      "......GGGG......",
      "................",
    ],
  },
  effect_burn: {
    palette: { O: "#e87a2a", R: "#c23b3b", Y: "#e8c34a", W: "#f8e8a8" },
    rows: [
      "................",
      ".......R........",
      ".......RR.......",
      "......RRR...R...",
      "......RRRR..RR..",
      ".....RRORR.RRR..",
      ".....ROORRRRRR..",
      "....RROOORRRRR..",
      "....ROOOOORRR...",
      "...RROOYOOORR...",
      "...ROOYYYOOOR...",
      "...ROYYWYYOOR...",
      "....OYWWWYYO....",
      "....OYYWYYYO....",
      ".....OYYYYO.....",
      "................",
    ],
  },
  effect_stun: {
    palette: { Y: "#e8c34a", W: "#f8e8a8", D: "#c89a2a" },
    rows: [
      "................",
      ".......YY.......",
      ".......YY.......",
      "......YWWY......",
      "......YWWY......",
      ".YY..YYWWYY..YY.",
      ".YYYYYYWWYYYYYY.",
      "..YYYYWWWWYYYY..",
      "...YYYWWWWYYY...",
      "....YYWWWWYY....",
      "...YYYYWWYYYY...",
      "...YYY.YY.YYY...",
      "..YY...YY...YY..",
      ".......YY.......",
      "........D.......",
      "................",
    ],
  },
  // ---------------- items ----------------
  sword: {
    palette: { W: "#d8dde4", D: "#9aa5b1", G: "#e8c34a", B: "#6b4a2b" },
    rows: [
      ".......WW.......",
      ".......WW.......",
      ".......WW.......",
      ".......WW.......",
      ".......WW.......",
      ".......WW.......",
      ".......WW.......",
      ".......WW.......",
      ".......WW.......",
      ".......DD.......",
      "....GGGGGGGG....",
      ".......BB.......",
      ".......BB.......",
      ".......BB.......",
      "......GBBG......",
      ".......GG.......",
    ],
  },
  axe: {
    palette: { W: "#c8ced6", D: "#8a939e", B: "#6b4a2b" },
    rows: [
      "....WWWW........",
      "...WWWWWW.......",
      "..WWWWWWWW......",
      "..WWWWBBWW......",
      "..WWWWBBWWW.....",
      "...WWWBBWWW.....",
      "....WWBBWW......",
      "......BB........",
      "......BB........",
      "......BB........",
      "......BB........",
      "......BB........",
      "......BB........",
      "......BB........",
      "......BB........",
      "................",
    ],
  },
  dagger: {
    palette: { W: "#d8dde4", D: "#9aa5b1", G: "#3a3f4a", B: "#23262e" },
    rows: [
      "................",
      "................",
      ".......WW.......",
      ".......WW.......",
      ".......WW.......",
      ".......WW.......",
      ".......WW.......",
      ".......DD.......",
      ".....GGGGGG.....",
      ".......BB.......",
      ".......BB.......",
      ".......BB.......",
      "......GBBG......",
      "................",
      "................",
      "................",
    ],
  },
  staff: {
    palette: { B: "#6b4a2b", D: "#4f371f", M: "#7a4ae6", W: "#c8a8ff" },
    rows: [
      "......MMMM......",
      ".....MMWWMM.....",
      ".....MWWWWM.....",
      ".....MMWWMM.....",
      "......MMMM......",
      ".......BB.......",
      ".......BB.......",
      ".......BB.......",
      ".......BB.......",
      ".......BB.......",
      ".......BB.......",
      ".......BB.......",
      ".......BB.......",
      ".......BB.......",
      ".......DD.......",
      "................",
    ],
  },
  armor: {
    palette: { S: "#9aa5b1", D: "#5c6670", G: "#e8c34a" },
    rows: [
      "................",
      "..SS........SS..",
      ".SSSS......SSSS.",
      ".SSSSSSSSSSSSSS.",
      ".SSSSSSSSSSSSSS.",
      ".SSDSSSSSSSSDSS.",
      "..SSSSSSSSSSSS..",
      "..SSSSSSSSSSSS..",
      "..SSSSGGGSSSSS..",
      "..SSSSSSSSSSSS..",
      "..SSSSSSSSSSSS..",
      "...SSSSSSSSSS...",
      "...SSSSSSSSSS...",
      "....SSSSSSSS....",
      "................",
      "................",
    ],
  },
  robe: {
    palette: { R: "#4a6be6", D: "#26398f", Y: "#e8c34a" },
    rows: [
      "................",
      "..RR........RR..",
      ".RRRR......RRRR.",
      ".RRRRRRRRRRRRRR.",
      ".RRRRRRRRRRRRRR.",
      ".RRDRRRRRRRRDRR.",
      "..RRRRYYRRRRRR..",
      "..RRRRYYRRRRRR..",
      "..RRRYYYYRRRRR..",
      "..RRRRYYRRRRRR..",
      "..RRRRRRRRRRRR..",
      "..RRRRRRRRRRRR..",
      ".RRRRRRRRRRRRRR.",
      ".RRRRRRRRRRRRRR.",
      "................",
      "................",
    ],
  },
  shield: {
    palette: { S: "#8a939e", D: "#5c6670", B: "#6b4a2b", G: "#e8c34a" },
    rows: [
      "...SSSSSSSSSS...",
      "..SSSSSSSSSSSS..",
      "..SSBBBBBBBBSS..",
      "..SSBBBBBBBBSS..",
      "..SSBBGGGGBBSS..",
      "..SSBBGGGGBBSS..",
      "..SSBBBBBBBBSS..",
      "..SSBBBBBBBBSS..",
      "..SSSBBBBBBSSS..",
      "...SSBBBBBBSS...",
      "...SSSBBBBSSS...",
      "....SSBBBBSS....",
      ".....SSBBSS.....",
      "......SSSS......",
      ".......SS.......",
      "................",
    ],
  },
  potion_hp: {
    palette: { R: "#e64a5f", D: "#a82a3a", G: "#c8ced6", B: "#6b4a2b", W: "#ffffff" },
    rows: [
      "......BBBB......",
      "......BBBB......",
      ".......GG.......",
      ".......GG.......",
      "......GGGG......",
      ".....GGGGGG.....",
      "....GGRRRRGG....",
      "....GRRRRRRG....",
      "...GRRRRRRRRG...",
      "...GRRWRRRRRG...",
      "...GRRRRRRRRG...",
      "...GRRRRRRRRG...",
      "....GRRRRRRG....",
      "....GGRRRRGG....",
      ".....GGGGGG.....",
      "................",
    ],
  },
  potion_mp: {
    palette: { R: "#4a6be6", D: "#26398f", G: "#c8ced6", B: "#6b4a2b", W: "#ffffff" },
    rows: [
      "......BBBB......",
      "......BBBB......",
      ".......GG.......",
      ".......GG.......",
      "......GGGG......",
      ".....GGGGGG.....",
      "....GGRRRRGG....",
      "....GRRRRRRG....",
      "...GRRRRRRRRG...",
      "...GRRWRRRRRG...",
      "...GRRRRRRRRG...",
      "...GRRRRRRRRG...",
      "....GRRRRRRG....",
      "....GGRRRRGG....",
      ".....GGGGGG.....",
      "................",
    ],
  },
  elixir: {
    palette: { R: "#7a4ae6", D: "#4f2aa8", G: "#c8ced6", B: "#6b4a2b", W: "#e8dcff" },
    rows: [
      "......BBBB......",
      "......BBBB......",
      ".......GG.......",
      ".......GG.......",
      "......GGGG......",
      ".....GGGGGG.....",
      "....GGRRRRGG....",
      "....GRRWRRRG....",
      "...GRRWWWRRRG...",
      "...GRRRWRRRRG...",
      "...GRRRRRRRRG...",
      "...GRRRRRRRRG...",
      "....GRRRRRRG....",
      "....GGRRRRGG....",
      ".....GGGGGG.....",
      "................",
    ],
  },
  bow: {
    palette: { B: "#8a5a2b", D: "#6b4520", S: "#d8dde4" },
    rows: [
      "........B.......",
      ".......BB.......",
      "......BB.S......",
      ".....BB..S......",
      "....BB...S......",
      "....B....S......",
      "...BB....S......",
      "...B.....S......",
      "...B.....S......",
      "...BB....S......",
      "....B....S......",
      "....BB...S......",
      ".....BB..S......",
      "......BB.S......",
      ".......BB.......",
      "........B.......",
    ],
  },
  hammer: {
    palette: { S: "#8a939e", D: "#5c6670", B: "#6b4a2b" },
    rows: [
      "....SSSSSSSS....",
      "...SSSSSSSSSS...",
      "...SSSSSSSSSS...",
      "...SSDSSSSDSS...",
      "...SSSSSSSSSS...",
      "....SSSSSSSS....",
      ".......BB.......",
      ".......BB.......",
      ".......BB.......",
      ".......BB.......",
      ".......BB.......",
      ".......BB.......",
      ".......BB.......",
      ".......BB.......",
      ".......BB.......",
      "................",
    ],
  },
  wand: {
    palette: { B: "#6b4a2b", D: "#4f371f", M: "#4ae6c8", W: "#c8fff0" },
    rows: [
      "..........WW....",
      ".........WMMW...",
      ".........MMMM...",
      "........WMMW....",
      "........MM......",
      ".......MM.......",
      "......BB........",
      "......BB........",
      ".....BB.........",
      ".....BB.........",
      "....BB..........",
      "....BB..........",
      "...BB...........",
      "...BB...........",
      "..DD............",
      "................",
    ],
  },
  cloak: {
    palette: { C: "#4a5a3d", D: "#33402a", G: "#e8c34a" },
    rows: [
      "................",
      "......GGGG......",
      ".....CCCCCC.....",
      "....CCCCCCCC....",
      "...CCCCCCCCCC...",
      "...CCCCCCCCCC...",
      "..CCCCCCCCCCCC..",
      "..CCCCCCCCCCCC..",
      "..CCCCCCCCCCCC..",
      ".CCCCCCCCCCCCCC.",
      ".CCCCCCCCCCCCCC.",
      ".CCCCCCCCCCCCCC.",
      ".CCDCCCCCCCCDCC.",
      ".CDCCCCCCCCCCDC.",
      ".DDDDDDDDDDDDDD.",
      "................",
    ],
  },
  potion_green: {
    palette: { R: "#4ec04e", D: "#2e8a2e", G: "#c8ced6", B: "#6b4a2b", W: "#ffffff" },
    rows: [
      "......BBBB......",
      "......BBBB......",
      ".......GG.......",
      ".......GG.......",
      "......GGGG......",
      ".....GGGGGG.....",
      "....GGRRRRGG....",
      "....GRRRRRRG....",
      "...GRRRRRRRRG...",
      "...GRRWRRRRRG...",
      "...GRRRRRRRRG...",
      "...GRRRRRRRRG...",
      "....GRRRRRRG....",
      "....GGRRRRGG....",
      ".....GGGGGG.....",
      "................",
    ],
  },
  salve: {
    palette: { P: "#e87a2a", D: "#b85a1a", G: "#c8ced6", W: "#f8e8a8" },
    rows: [
      "................",
      "................",
      "................",
      "....GGGGGGGG....",
      "....G......G....",
      "...GGGGGGGGGG...",
      "...GPPPPPPPPG...",
      "...GPPWPPPPPG...",
      "...GPPPPPPPPG...",
      "...GPPPPPPPPG...",
      "...GPPPPPPPPG...",
      "...GGGGGGGGGG...",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  apple: {
    palette: { R: "#c23b3b", D: "#8a2525", G: "#4a8f40", B: "#6b4a2b", W: "#e88a8a" },
    rows: [
      "................",
      "................",
      "........B.......",
      ".......BG.......",
      ".......B.G......",
      "....RRRRRRRR....",
      "...RRRRRRRRRR...",
      "..RRWRRRRRRRRR..",
      "..RWRRRRRRRRRR..",
      "..RRRRRRRRRRRR..",
      "..RRRRRRRRRRRR..",
      "..RRRRRRRRRRDD..",
      "...RRRRRRRRDD...",
      "....RRRRRRRR....",
      ".....RR..RR.....",
      "................",
    ],
  },
  meat: {
    palette: { M: "#b85a4a", D: "#8a3d30", B: "#e8e4d8", W: "#d88a7a" },
    rows: [
      "................",
      "................",
      "..MMMM..........",
      ".MMMMMM.........",
      ".MMWMMMM........",
      ".MMMMMMMM.......",
      "..MMMMMMMM......",
      "...MMMMMMMM.....",
      "....MMMMMMMM....",
      ".....MMWMMMMM...",
      "......MMMMMMM...",
      ".......MMMMM....",
      "........DDBB....",
      "..........BBB...",
      "...........BB...",
      "................",
    ],
  },
  pelt: {
    palette: { P: "#8a6a4a", D: "#6b4e33", L: "#a8845c" },
    rows: [
      "................",
      "..PP........PP..",
      ".PPPP......PPPP.",
      ".PPPPPPPPPPPPPP.",
      "..PPPPPPPPPPPP..",
      "..PPLPPPPPLPPP..",
      "..PPPPPPPPPPPP..",
      "..PPPPPDPPPPPP..",
      "..PPPPPPPPPPPP..",
      "..PPPPPPPPLPPP..",
      "..PPLPPPPPPPPP..",
      "..PPPPPPPPPPPP..",
      ".PPPP......PPPP.",
      "..PP........PP..",
      "................",
      "................",
    ],
  },
  horn: {
    palette: { H: "#e8e4d8", D: "#b0aa98", R: "#c23b3b" },
    rows: [
      "................",
      "............HH..",
      "...........HHH..",
      "..........HHH...",
      ".........HHHH...",
      "........HHHH....",
      ".......HHHH.....",
      "......HHHH......",
      ".....HHHH.......",
      "....HHHH........",
      "....HHH.........",
      "...HHHH.........",
      "...HHH..........",
      "...RRH..........",
      "...RR...........",
      "................",
    ],
  },
  herb: {
    palette: { G: "#4a8f40", D: "#2e6628", F: "#7ab648" },
    rows: [
      "................",
      "................",
      "......G..G......",
      "..F...G..G...F..",
      "..G..FG..GF..G..",
      "..G..GG..GG..G..",
      "...G.GD..DG.G...",
      "...GGGD..DGGG...",
      "....DGG..GGD....",
      ".....DG..GD.....",
      "......D..D......",
      "......D..D......",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  reed: {
    palette: { R: "#5a7a3d", D: "#3d5428", B: "#8a6a4a" },
    rows: [
      "................",
      "....B...........",
      "....B......B....",
      "....R......B....",
      "....R..R...R....",
      "....R..R...R....",
      "....R..R...R....",
      "....R..R...R....",
      "....D..R...D....",
      "....D..D...D....",
      "....D..D...D....",
      "....D..D...D....",
      "....D..D...D....",
      "................",
      "................",
      "................",
    ],
  },
  shard: {
    palette: { O: "#e87a2a", Y: "#e8c34a", D: "#8a4515", W: "#f8e8a8" },
    rows: [
      "................",
      "................",
      "................",
      ".......O........",
      "......OYO.......",
      "......OYO.......",
      ".....OYWYO......",
      ".....OYWYO......",
      "....OYWWYYO.....",
      "....OYYYYYO.....",
      "...OOYYYYYOO....",
      "...DOOOOOOOD....",
      "....DDDDDDD.....",
      "................",
      "................",
      "................",
    ],
  },
  bread: {
    palette: { B: "#d8a85a", D: "#a87a3a", W: "#f0d8a8" },
    rows: [
      "................",
      "................",
      "................",
      "................",
      "....BBBBBBB.....",
      "...BBBBBBBBBB...",
      "..BBWWBBBBBBBB..",
      "..BBBBWWBBBBBB..",
      ".BBBBBBBWWBBBBB.",
      ".BBBBBBBBBWWBBB.",
      ".DBBBBBBBBBBBBD.",
      ".DDBBBBBBBBBBDD.",
      "..DDDDDDDDDDDD..",
      "................",
      "................",
      "................",
    ],
  },
  cheese: {
    palette: { Y: "#e8c34a", D: "#c89a2a", O: "#a87a1a" },
    rows: [
      "................",
      "................",
      "................",
      "......YYYYY.....",
      "....YYYYYYYYY...",
      "..YYYYYYYYYYYY..",
      ".YYYYYYYYYYYYYY.",
      ".YYODYYYYYODYYY.",
      ".YYYYYYYYYYYYYY.",
      ".YYYYYODYYYYYYY.",
      ".YYYYYYYYYYODYY.",
      ".YYODYYYYYYYYYY.",
      ".DDDDDDDDDDDDDD.",
      ".DDDDDDDDDDDDDD.",
      "................",
      "................",
    ],
  },
  gold: {
    palette: { Y: "#e8c34a", D: "#c89a2a", W: "#f8e8a8" },
    rows: [
      "................",
      "................",
      "................",
      "......YYYY......",
      "....YYYYYYYY....",
      "...YYWWYYYYYY...",
      "...YWYYYYYYYY...",
      "..YYYYYYYYYYYY..",
      "..YYYYYDDYYYYY..",
      "..YYYYDYYDYYYY..",
      "..YYYYYDDYYYYY..",
      "...YYYYYYYYYY...",
      "...YYYYYYYYYY...",
      "....YYYYYYYY....",
      "......DDDD......",
      "................",
    ],
  },
  gem: {
    palette: { G: "#4ae6c8", D: "#2aa890", W: "#c8fff0" },
    rows: [
      "................",
      "................",
      "................",
      "....GGGGGGGG....",
      "...GWGGGGGGGG...",
      "..GWWGGGGGGGGG..",
      "..GWGGGGGGGGDG..",
      "...GGGGGGGGDD...",
      "....GGGGGGDD....",
      ".....GGGGDD.....",
      "......GGDD......",
      ".......GD.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  scale: {
    palette: { R: "#c23b3b", D: "#8a2525", W: "#e88a8a" },
    rows: [
      "................",
      "................",
      "....RRRRRRRR....",
      "...RRRRRRRRRR...",
      "...RWRRRRRRRR...",
      "...RWRRRRRRRR...",
      "...RRRRRRRRDR...",
      "....RRRRRRDD....",
      "....RRRRRRDD....",
      ".....RRRRDD.....",
      ".....RRRRDD.....",
      "......RRDD......",
      "......RRDD......",
      ".......DD.......",
      "................",
      "................",
    ],
  },
};

// ---------------- hero looks: palette-swap appearance variants ----------------
// Every sprite is a grid + palette, so appearance customization is nearly
// free: same rows, swapped skin (F) and outfit (H/D) colors per look.
// New classes reuse a proven silhouette with their own palette identity.
sprites.hero_ranger = {
  palette: { ...sprites.hero_rogue.palette, H: "#3b6b2e", D: "#26471e", K: "#8a6238" },
  rows: sprites.hero_rogue.rows,
};
sprites.hero_paladin = {
  palette: { ...sprites.hero_warrior.palette, H: "#d8cfa8", D: "#a89058", R: "#4a6be6" },
  rows: sprites.hero_warrior.rows,
};
sprites.hero_necromancer = {
  palette: { ...sprites.hero_mage.palette, H: "#3b2d56", D: "#241a38", R: "#8a4ad6", Y: "#4ae6c8" },
  rows: sprites.hero_mage.rows,
};

const HERO_LOOKS = {
  hero_ranger: [{}, { F: "#c98d5f" }, { H: "#6b4a2b", D: "#47301c" }, { F: "#8a5a3b", H: "#4a4f5a", D: "#2e323b" }],
  hero_paladin: [{}, { F: "#c98d5f" }, { H: "#9aa5b1", D: "#5c6670" }, { F: "#8a5a3b", H: "#8a2d2d", D: "#571c1c" }],
  hero_necromancer: [
    {},
    { F: "#c98d5f" },
    { H: "#2d4a56", D: "#1a2e38" },
    { F: "#8a5a3b", H: "#4a1c1c", D: "#301111" },
  ],
  hero_warrior: [{}, { F: "#c98d5f" }, { H: "#b1926a", D: "#7d6644" }, { F: "#8a5a3b", H: "#6b7280", D: "#454b57" }],
  hero_mage: [{}, { F: "#c98d5f" }, { H: "#8a4ad6", D: "#5b2d8f" }, { F: "#8a5a3b", H: "#3b8a4a", D: "#26592e" }],
  hero_rogue: [{}, { F: "#c98d5f" }, { H: "#5a3a3f", D: "#38262a" }, { F: "#8a5a3b", H: "#2e3a5a", D: "#1e2740" }],
  hero_cleric: [{}, { F: "#c98d5f" }, { H: "#d6c08a", D: "#a89058" }, { F: "#8a5a3b", H: "#8a93a5", D: "#5c6670" }],
};
const HERO_VARIANTS = [];
for (const [base, looks] of Object.entries(HERO_LOOKS)) {
  looks.forEach((swap, i) => {
    if (i === 0) return; // look 0 is the original sprite
    const name = `${base}_l${i}`;
    sprites[name] = { palette: { ...sprites[base].palette, ...swap }, rows: sprites[base].rows };
    HERO_VARIANTS.push(name);
  });
}

// ---------------- the wardrobe: equipment drawn for the hero's body ----------------
// Worn overlays are 16x16 transparent grids fitted to the shared hero
// anatomy (head rows 2-6, torso 8-12, hands at the sides). The runtime
// composes them onto the walk sheets per equipment set - one grid per
// silhouette here, palette variants generated below, like the roofs.
const WEAR_GRIDS = {
  // a blade held at the right hand, edge up
  wear_sword: {
    palette: { B: "#c8ccd8", D: "#8a8f9a", H: "#8a5a2b" },
    rows: [
      "................",
      ".............B..",
      ".............B..",
      ".............B..",
      ".............B..",
      ".............B..",
      ".............B..",
      ".............B..",
      ".............B..",
      "............DBD.",
      ".............H..",
      ".............H..",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  wear_dagger: {
    palette: { B: "#c8ccd8", D: "#8a8f9a", H: "#2a2d35" },
    rows: [
      "................",
      "................",
      "................",
      "................",
      "................",
      ".............B..",
      ".............B..",
      ".............B..",
      ".............B..",
      "............DBD.",
      ".............H..",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  wear_axe: {
    palette: { B: "#c8ccd8", D: "#8a8f9a", H: "#8a5a2b" },
    rows: [
      "................",
      "................",
      "............BB..",
      "...........BBB..",
      "...........BBBB.",
      "...........BBB..",
      "............HB..",
      ".............H..",
      ".............H..",
      ".............H..",
      ".............H..",
      ".............H..",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  wear_hammer: {
    palette: { B: "#8a8f9a", D: "#5c6070", H: "#8a5a2b" },
    rows: [
      "................",
      "................",
      "...........BBBB.",
      "...........BBBB.",
      "...........BDDB.",
      "...........BBBB.",
      ".............H..",
      ".............H..",
      ".............H..",
      ".............H..",
      ".............H..",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  wear_bow: {
    palette: { W: "#8a5a2b", S: "#e8e0cc" },
    rows: [
      "................",
      "................",
      "............W...",
      "...........W.S..",
      "..........W..S..",
      "..........W..S..",
      "..........W..S..",
      "..........W..S..",
      "..........W..S..",
      "..........W..S..",
      "..........W..S..",
      "...........W.S..",
      "............W...",
      "................",
      "................",
      "................",
    ],
  },
  wear_staff: {
    palette: { W: "#8a5a2b", G: "#4ae6c8" },
    rows: [
      "................",
      "............GG..",
      "...........GGGG.",
      "............GG..",
      ".............W..",
      ".............W..",
      ".............W..",
      ".............W..",
      ".............W..",
      ".............W..",
      ".............W..",
      ".............W..",
      ".............W..",
      ".............W..",
      "................",
      "................",
    ],
  },
  // Dragonbane: the one blade that gets its own portrait
  wear_dragonbane: {
    palette: { B: "#3a3f4a", E: "#e64a5f", H: "#e8c34a" },
    rows: [
      "............E...",
      "............BE..",
      "............BE..",
      "............BE..",
      "............BE..",
      "............BE..",
      "............BE..",
      "............BE..",
      "............BE..",
      "...........HBH..",
      "............H...",
      "............H...",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  // the torso plate: covers the outfit rows, arms stay free
  wear_plate: {
    palette: { P: "#9aa5b1", D: "#5c6670", R: "#c8ccd8" },
    rows: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "...PPPPPPPP.....",
      "..PPRPPPPRPP....",
      "..PPPPPPPPPP....",
      "..PPDPPPPDPP....",
      "..PPPPPPPPPP....",
      "................",
      "................",
      "................",
    ],
  },
  // the robe: drapes past the belt to the ankles
  wear_robe: {
    palette: { P: "#7a4a8f", D: "#603a70", R: "#e8c34a" },
    rows: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "...PPPPPPPP.....",
      "..PPPPPPPPPP....",
      "..PPPRRRRPPP....",
      "..PPPPPPPPPP....",
      "..PPPPPPPPPP....",
      "...PPPPPPPP.....",
      "...PPP..PPP.....",
      "................",
    ],
  },
  // the helm dome: covers hair and brows, face stays open
  wear_helm: {
    palette: { M: "#9aa5b1", D: "#5c6670", K: "#2a2d35" },
    rows: [
      "................",
      "................",
      "....MMMMMM......",
      "...MMMMMMMM.....",
      "...MDM..MDM.....",
      "...MDM..MDM.....",
      "...M......M.....",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  // the wyrm visor: the dome plus a crest
  wear_helm_crest: {
    palette: { M: "#6b6f7a", D: "#454e60", C: "#e64a5f" },
    rows: [
      "......CC........",
      "......CC........",
      "....MMMMMM......",
      "...MMMMMMMM.....",
      "...MDM..MDM.....",
      "...MDM..MDM.....",
      "...M......M.....",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  // shields ride the left arm
  wear_shield_small: {
    palette: { S: "#8a6238", D: "#5c3f24", B: "#c8ccd8" },
    rows: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "..SSS...........",
      ".SSSSS..........",
      ".SSBSS..........",
      ".SSSSS..........",
      "..SSS...........",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  wear_shield_tower: {
    palette: { S: "#8a8f9a", D: "#5c6070", B: "#e8c34a" },
    rows: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      ".SSSS...........",
      ".SDDS...........",
      ".SDBS...........",
      ".SDDS...........",
      ".SDDS...........",
      ".SSSS...........",
      "..SS............",
      "................",
      "................",
      "................",
    ],
  },
};
for (const [name, def] of Object.entries(WEAR_GRIDS)) sprites[name] = def;

// palette variants: same silhouette, the tier's colors
const WEAR_VARIANTS = {
  wear_sword_rusty: ["wear_sword", { B: "#8a7a5a", D: "#6b5a3a" }],
  wear_sword_dark: ["wear_sword", { B: "#3a3f4a", D: "#22242b", H: "#603a70" }],
  wear_plate_leather: ["wear_plate", { P: "#8a6238", D: "#5c3f24", R: "#a87a4a" }],
  wear_plate_runic: ["wear_plate", { P: "#4a4e58", D: "#2e323b", R: "#4ae6c8" }],
  wear_plate_scaled: ["wear_plate", { P: "#3e8f5c", D: "#2d6b44", R: "#84965a" }],
  wear_robe_shadow: ["wear_robe", { P: "#3a3f4a", D: "#22242b", R: "#8a4ad6" }],
  wear_robe_cloak: ["wear_robe", { P: "#6b4a2b", D: "#47301c", R: "#8a6238" }],
  wear_helm_leather: ["wear_helm", { M: "#8a6238", D: "#5c3f24", K: "#2a2118" }],
  wear_shield_ward: ["wear_shield_small", { S: "#2d6b44", D: "#1d4a2e", B: "#4ae6c8" }],
};
for (const [name, [base, swap]] of Object.entries(WEAR_VARIANTS)) {
  sprites[name] = { palette: { ...WEAR_GRIDS[base].palette, ...swap }, rows: WEAR_GRIDS[base].rows };
}

// ---------------- actor outlines ----------------
// Every living thing gets a 1px dark outline so it pops off the terrain,
// baked into the base grid so animations and both renderers inherit it.
const MONSTERS = [
  "slime",
  "goblin",
  "skeleton",
  "wolf",
  "orc",
  "ghost",
  "golem",
  "troll",
  "wyvern",
  "dragon",
  "boneknight",
  "shade",
  "mimic",
  "imp",
  "lich",
];
const NPCS = ["villager", "villager_woman", "elder", "innkeeper", "smith", "alchemist", "merchant"];
const HEROES = [
  "hero_warrior",
  "hero_mage",
  "hero_rogue",
  "hero_cleric",
  "hero_ranger",
  "hero_paladin",
  "hero_necromancer",
  ...HERO_VARIANTS,
];

function outlined({ rows, palette }) {
  const out = rows.map((r) => r.split(""));
  for (let y = 0; y < 16; y++) {
    for (let x = 0; x < 16; x++) {
      if (rows[y][x] !== ".") continue;
      const solid = [
        [0, -1],
        [0, 1],
        [-1, 0],
        [1, 0],
      ].some(([dx, dy]) => {
        const c = rows[y + dy]?.[x + dx];
        return c && c !== "." && c !== "o";
      });
      if (solid) out[y][x] = "o";
    }
  }
  return { palette: { ...palette, o: "#14151c" }, rows: out.map((r) => r.join("")) };
}
for (const name of [...MONSTERS, ...NPCS, ...HEROES]) {
  if (sprites[name].palette.o) throw new Error(`${name} already uses the outline char`);
  sprites[name] = outlined(sprites[name]);
}

// ---------------- rank looks: the promoted wear it ----------------
// Every hero variant gets three ascended forms: garb brightens with rank and
// the outline turns from shadow to gold to radiant. Skin stays skin.
const RANK_OUTLINES = [null, "#232838", "#4a3a12", "#0f3d35"];
function brighten(hex, factor) {
  const n = Number.parseInt(hex.slice(1), 16);
  const lift = (shift) => Math.min(255, Math.round(((n >> shift) & 255) * factor));
  return `#${((lift(16) << 16) | (lift(8) << 8) | lift(0)).toString(16).padStart(6, "0")}`;
}
const HERO_RANKS = [];
for (const name of HEROES.slice()) {
  for (let r = 1; r <= 3; r++) {
    const src = sprites[name];
    const palette = {};
    for (const [ch, color] of Object.entries(src.palette)) {
      if (ch === "F") palette[ch] = color;
      else if (ch === "o") palette[ch] = RANK_OUTLINES[r];
      else palette[ch] = brighten(color, 1 + r * 0.09);
    }
    sprites[`${name}_r${r}`] = { palette, rows: src.rows };
    HERO_RANKS.push(`${name}_r${r}`);
  }
}
HEROES.push(...HERO_RANKS);

const names = Object.keys(sprites);
for (const name of names) {
  const { rows, palette } = sprites[name];
  if (rows.length !== 16 || rows.some((r) => r.length !== 16)) throw new Error(`${name} is not 16x16`);
  const { buf, w, h } = renderSprite(rows, palette);
  writeFileSync(join(OUT, `${name}.png`), encodePng(w, h, buf));
}

// ---------------- animation sheets (G1) ----------------
// Animations are generated the same way the art is: pure transforms over the
// base 16x16 grids, composed into a horizontal strip PNG plus an atlas.json
// the renderer reads. No hand-drawn frames, so the whole thing stays
// deterministic for the CI sprite-sync check.
const BLANK = ".".repeat(16);
/** Slide the whole grid up by d rows (blanks fill the bottom). */
const bobUp = (rows, d = 1) => rows.slice(d).concat(Array(d).fill(BLANK));
/** Slide the whole grid down by d rows (blanks fill the top). */
const bobDown = (rows, d = 1) =>
  Array(d)
    .fill(BLANK)
    .concat(rows.slice(0, 16 - d));
/** Wrap-shift horizontally; safe on seamless tiles, gives flowing water. */
const shiftXWrap = (rows, dx) => {
  const s = ((dx % 16) + 16) % 16;
  return rows.map((r) => r.slice(16 - s) + r.slice(0, 16 - s));
};
/** Wrap-shift vertically; combined with shiftXWrap it makes terrain shimmer. */
const shiftYWrap = (rows, dy) => {
  const s = ((dy % 16) + 16) % 16;
  return rows.slice(16 - s).concat(rows.slice(0, 16 - s));
};
/** Nudge just the bottom rows (feet) sideways for a walk step; non-wrapping. */
const feet = (rows, dx) =>
  rows.map((r, y) => {
    if (y < 13) return r;
    if (dx > 0) return ".".repeat(dx) + r.slice(0, 16 - dx);
    if (dx < 0) return r.slice(-dx) + ".".repeat(-dx);
    return r;
  });

const walkFrames = (b) => [b, feet(bobUp(b, 1), 1), b, feet(bobUp(b, 1), -1)];
const idleFrames = (b) => [b, bobDown(b, 1)];
const shimmerFrames = (b) => [b, shiftXWrap(b, 1), shiftXWrap(b, 2), shiftXWrap(b, 3)];
// Terrain sway wraps in both axes so tiles stay opaque and seamless: the
// specks and blades jiggle diagonally, reading as wind at low fps.
const swayFrames = (b) => [b, shiftXWrap(shiftYWrap(b, 1), 1)];

const anims = [
  ...HEROES.map((base) => ({ name: `${base}_walk`, base, fps: 6, facing: "front", frames: walkFrames })),
  ...NPCS.map((base) => ({ name: `${base}_idle`, base, fps: 2, frames: idleFrames })),
  ...MONSTERS.map((base) => ({ name: `${base}_idle`, base, fps: 2, frames: idleFrames })),
  { name: "water_shimmer", base: "tile_water", fps: 4, frames: shimmerFrames },
  { name: "grass_sway", base: "tile_grass", fps: 2, frames: swayFrames },
  { name: "grass2_sway", base: "tile_grass2", fps: 2, frames: swayFrames },
  { name: "grass3_sway", base: "tile_grass3", fps: 2, frames: swayFrames },
  { name: "forest_sway", base: "tile_forest", fps: 2, frames: swayFrames },
  { name: "flowers_sway", base: "tile_flowers", fps: 2, frames: swayFrames },
  { name: "marsh_sway", base: "tile_marsh", fps: 2, frames: swayFrames },
];

/** Lay frames left to right into one 16-tall strip. */
function renderSheet(frames, palette) {
  const W = 16 * frames.length;
  const sheet = Buffer.alloc(W * 16 * 4);
  frames.forEach((rows, i) => {
    const { buf } = renderSprite(rows, palette);
    const ox = i * 16;
    for (let y = 0; y < 16; y++) {
      for (let x = 0; x < 16; x++) {
        const si = (y * 16 + x) * 4;
        if (buf[si + 3] === 0) continue;
        buf.copy(sheet, (y * W + ox + x) * 4, si, si + 4);
      }
    }
  });
  return { buf: sheet, w: W, h: 16 };
}

const atlas = { frameSize: 16, animations: {} };
for (const anim of anims) {
  const src = sprites[anim.base];
  if (!src) throw new Error(`Animation ${anim.name} has no base sprite "${anim.base}"`);
  const frames = anim.frames(src.rows);
  const { buf, w, h } = renderSheet(frames, src.palette);
  writeFileSync(join(OUT, `${anim.name}.png`), encodePng(w, h, buf));
  atlas.animations[anim.name] = {
    sheet: `${anim.name}.png`,
    frames: frames.length,
    fps: anim.fps,
    loop: true,
    ...(anim.facing ? { facing: anim.facing } : {}),
  };
}
writeFileSync(join(OUT, "atlas.json"), JSON.stringify(atlas, null, 2) + "\n");

// ---------------- voxel source (PIX-111) ----------------
// The 3D renderer extrudes the same grids the PNGs are baked from: every
// sprite's rows + palette, verbatim. One art source of truth - editing a
// sprite here reshapes its voxel model with no extra work.
const voxels = { art: 16, sprites: {} };
for (const name of names) {
  voxels.sprites[name] = { rows: sprites[name].rows, palette: sprites[name].palette };
}
writeFileSync(join(OUT, "voxels.json"), JSON.stringify(voxels) + "\n");

// x8 preview sheet for eyeballing the art (not shipped in the app)
const SCALE = 8,
  COLS = 7,
  CELL = 16 * SCALE + 8;
const rowsCount = Math.ceil(names.length / COLS);
const sheet = Buffer.alloc(COLS * CELL * rowsCount * CELL * 4);
// dark checker background so light sprites stay visible
for (let i = 0; i < sheet.length; i += 4) {
  sheet[i] = 30;
  sheet[i + 1] = 32;
  sheet[i + 2] = 38;
  sheet[i + 3] = 255;
}
names.forEach((name, idx) => {
  const { buf, w, h } = renderSprite(sprites[name].rows, sprites[name].palette, SCALE);
  const ox = (idx % COLS) * CELL + 4,
    oy = Math.floor(idx / COLS) * CELL + 4;
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const si = (y * w + x) * 4;
      if (buf[si + 3] === 0) continue;
      const di = ((oy + y) * COLS * CELL + ox + x) * 4;
      buf.copy(sheet, di, si, si + 4);
    }
  }
});
writeFileSync(join(ROOT, "scripts", "preview.png"), encodePng(COLS * CELL, rowsCount * CELL, sheet));
console.log(
  `Wrote ${names.length} sprites, ${anims.length} animation sheets + atlas.json to public/sprites/ and scripts/preview.png`,
);
