class_name Interactables
## Treasure chests and door signs exported from the web game
## (assets/maps/interactables.json, regenerated by pnpm godot:sync).
## Placement validation (walkable, portal-free) already ran web-side.

static var _doc := {}


static func _data() -> Dictionary:
	if _doc.is_empty():
		var raw := FileAccess.get_file_as_string("res://assets/maps/interactables.json")
		_doc = JSON.parse_string(raw)
	return _doc


static func chests_on(map_id: String) -> Array:
	return _data()["chests"].filter(func(chest: Dictionary) -> bool: return chest["mapId"] == map_id)


static func signs_on(map_id: String) -> Array:
	return _data()["signs"].get(map_id, [])


static func waypoints() -> Array:
	return _data()["waypoints"]


## A waypoint unlocks the moment its marker tile has been seen
## (ported from src/world/waypoints.ts).
static func waypoint_discovered(waypoint: Dictionary, discovered: Dictionary) -> bool:
	var at := Vector2i(int(waypoint["at"]["x"]), int(waypoint["at"]["y"]))
	return Discovery.is_discovered(discovered, waypoint["mapId"], at)


## Discovered AND staffed: a settler-run post only works once they moved in.
static func waypoint_usable(
	waypoint: Dictionary, discovered: Dictionary, settlers: Array
) -> bool:
	if not waypoint_discovered(waypoint, discovered):
		return false
	var required: String = waypoint.get("requiresSettler", "")
	return required == "" or required in settlers


## What to draw for this treasure right now; "" means nothing is left
## (ported from chestSpriteName in src/world/chests.ts).
static func sprite_name(chest: Dictionary, opened: bool) -> String:
	if chest["look"] == "chest":
		return "chest_open" if opened else "chest_closed"
	if opened:
		return ""
	return "road_glint" if chest["look"] == "glint" else "herb_patch"


## "iron_sword" -> "Iron Sword"; placeholder until the economy port (PIX-124)
## brings real item names across.
static func item_label(item_id: String) -> String:
	return item_id.capitalize()


static func loot_text(chest: Dictionary) -> String:
	var loot: Dictionary = chest.get("loot", {})
	match loot.get("kind", ""):
		"gold":
			return "You found %d gold!" % int(loot["amount"])
		"item":
			return "You found %d× %s!" % [int(loot["qty"]), item_label(loot["itemId"])]
		"gear":
			return "You found %s!" % item_label(loot["itemId"])
	return ""
