class_name Interactables
## Treasure chests and door signs exported from the web game
## (assets/maps/interactables.json, regenerated by pnpm godot:sync).
## Placement validation (walkable, portal-free) already ran web-side.

static var _doc := {}


static func _data() -> Dictionary:
	if _doc.is_empty():
		var raw := FileAccess.get_file_as_string("res://assets/maps/interactables.json")
		var doc: Dictionary = JSON.parse_string(raw)
		var signs: Dictionary = doc["signs"].duplicate(true)
		_doc = Text.localize(doc)
		# A sign's label is its id (PIX-196): the icon and the door go by it;
		# where it's shown, the label translates itself.
		_doc["signs"] = signs
	return _doc


static func chests_on(map_id: String) -> Array:
	return _data()["chests"].filter(func(chest: Dictionary) -> bool: return chest["mapId"] == map_id)


## Door signs; the house sign reads HOME instead of FOR SALE once it is owned.
static func signs_on(map_id: String, house_owned := false) -> Array:
	if house_owned and _data()["signsHouseOwned"].has(map_id):
		return _data()["signsHouseOwned"][map_id]
	return _data()["signs"].get(map_id, [])


static func waypoints() -> Array:
	return _data()["waypoints"]


## A waypoint unlocks the moment its marker tile has been seen
## (ported from src/world/waypoints.ts).
static func waypoint_discovered(waypoint: Dictionary, discovered: Dictionary) -> bool:
	var at := Vector2i(int(waypoint["at"]["x"]), int(waypoint["at"]["y"]))
	return Discovery.is_discovered(discovered, waypoint["mapId"], at)


## Discovered AND staffed: a settler-run post only works once they moved in.
static func waypoint_usable(
	waypoint: Dictionary, discovered: Dictionary, settlers: Array
) -> bool:
	if not waypoint_discovered(waypoint, discovered):
		return false
	var required: String = waypoint.get("requiresSettler", "")
	return required == "" or required in settlers


## What to draw for this treasure right now; "" means nothing is left
## (ported from chestSpriteName in src/world/chests.ts).
static func sprite_name(chest: Dictionary, opened: bool) -> String:
	if chest["look"] == "chest":
		return "chest_open" if opened else "chest_closed"
	if opened:
		return ""
	return "road_glint" if chest["look"] == "glint" else "herb_patch"

